import Link from "next/link";
import { saveService } from "@/app/dashboard/operations-actions";
import { FormMessage } from "@/components/form-message";
import { SubmitButton } from "@/components/submit-button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { formatDuration, formatMoney } from "@/lib/operations";

const textarea = "mt-2 min-h-24 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-admin-text shadow-sm focus-visible:border-brand-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-100";
const select = "mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-admin-text shadow-sm focus-visible:border-brand-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-100";
const Field = ({label,children}:{label:string;children:React.ReactNode}) => <label className="block text-sm font-semibold text-slate-800">{label}{children}</label>;
export type ServiceRecord={id:string;name:string;category_id:string|null;description:string|null;short_description:string|null;code:string|null;duration_minutes:number;base_price_centavos:number;is_add_on:boolean;parent_service_id:string|null};
type Price={branch_id?:string|null;vehicle_class:string|null;price_centavos:number};

export function ServiceForm({service,categories,branches,services=[],prices,availableBranchIds,error,automotivePricing=true,serviceLabel="Service",idPrefix="service"}:{service?:ServiceRecord;categories:{id:string;name:string}[];branches:{id:string;name:string}[];services?:{id:string;name:string}[];prices?:Price[];availableBranchIds?:string[];error?:string;automotivePricing?:boolean;serviceLabel?:string;idPrefix?:string}) {
  const priceText=(rows:Price[])=>rows.map(price=>`${price.vehicle_class}=${(price.price_centavos/100).toFixed(2)}`).join("\n");
  return <Card className="p-5 sm:p-7"><FormMessage error={error}/><form id={`${idPrefix}-${service?"edit":"create"}-form`} action={saveService} className="mt-5 grid gap-5 sm:grid-cols-2">
    {service&&<input type="hidden" name="id" value={service.id}/>}<Field label={`${serviceLabel} name *`}><Input id={`${idPrefix}-name-input`} required name="name" maxLength={160} defaultValue={service?.name}/></Field>
    <Field label="Category"><select id={`${idPrefix}-category-select`} className={select} name="categoryId" defaultValue={service?.category_id??""}><option value="">Uncategorized</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></Field>
    <Field label="Base price (PHP) *"><Input id={`${idPrefix}-base-price-input`} required inputMode="decimal" name="basePrice" defaultValue={service?(service.base_price_centavos/100).toFixed(2):""} placeholder="300.00"/></Field>
    <Field label="Estimated duration (minutes) *"><Input id={`${idPrefix}-duration-input`} required type="number" min={1} max={10080} name="durationMinutes" defaultValue={service?.duration_minutes}/></Field>
    <Field label="Internal code"><Input name="code" maxLength={50} defaultValue={service?.code??""}/></Field>
    <Field label="Add-on compatibility"><select className={select} name="parentServiceId" defaultValue={service?.parent_service_id??""}><option value="">Any service / standalone</option>{services.filter(candidate=>candidate.id!==service?.id).map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select></Field>
    <div className="sm:col-span-2"><Field label="Short description"><Input name="shortDescription" maxLength={300} defaultValue={service?.short_description??""}/></Field></div>
    <div className="sm:col-span-2"><Field label="Description"><textarea className={textarea} name="description" maxLength={2000} defaultValue={service?.description??""}/></Field></div>
    {automotivePricing?<div className="sm:col-span-2"><Field label="Organization vehicle-class prices"><textarea className={textarea} name="vehiclePrices" placeholder={"sedan=300\nsuv=400\npickup=450"} defaultValue={priceText(prices?.filter(price=>!price.branch_id&&price.vehicle_class)??[])}/></Field><p className="mt-1 text-xs text-zinc-500">Optional. Enter one class=price per line.</p></div>:null}
    {branches.map(branch=>{const base=prices?.find(price=>price.branch_id===branch.id&&!price.vehicle_class);return <fieldset className="rounded-xl border border-zinc-200 p-4 sm:col-span-2" key={branch.id}><legend className="px-1 font-bold">{branch.name} price overrides</legend><div className="grid gap-4 sm:grid-cols-2"><Field label="Branch base price (PHP)"><Input inputMode="decimal" name={`branchBasePrice:${branch.id}`} defaultValue={base?(base.price_centavos/100).toFixed(2):""}/></Field>{automotivePricing?<Field label="Vehicle-class overrides"><textarea className={textarea} name={`branchVehiclePrices:${branch.id}`} placeholder={"suv=450\npickup=500"} defaultValue={priceText(prices?.filter(price=>price.branch_id===branch.id&&price.vehicle_class)??[])}/></Field>:null}</div></fieldset>})}
    <fieldset className="sm:col-span-2"><legend className="text-sm font-semibold">Branch availability</legend><label className="mt-2 flex min-h-11 items-center gap-2"><input type="checkbox" name="allBranches" defaultChecked={!availableBranchIds?.length}/> Available at all branches</label><div className="grid gap-2 sm:grid-cols-2">{branches.map(branch=><label className="flex min-h-11 items-center gap-2 rounded-xl border border-zinc-200 px-3" key={branch.id}><input type="checkbox" name="branchIds" value={branch.id} defaultChecked={availableBranchIds?.includes(branch.id)}/>{branch.name}</label>)}</div></fieldset>
    <label className="flex min-h-11 items-center gap-2"><input type="checkbox" name="isAddOn" defaultChecked={service?.is_add_on}/> This is an add-on</label>
    <div className="flex gap-3 sm:col-span-2"><SubmitButton id={`${idPrefix}-save-button`} pendingText="Saving…">Save {serviceLabel.toLowerCase()}</SubmitButton><Link id={`${idPrefix}-cancel-button`} className="inline-flex min-h-11 items-center px-3 font-bold text-zinc-700" href="/dashboard/services">Cancel</Link></div>
  </form></Card>;
}

type Choice={id:string;name:string}; type VehicleChoice={id:string;customer_id:string;label:string}; type ServiceChoice={id:string;name:string;base_price_centavos:number;duration_minutes:number};
type StaffChoice={id:string;name:string;branchIds:string[]};type ResourceChoice={id:string;name:string;branch_id:string;capacity:number};
export function VisitForm({mode,action,appointment,defaults,branches,customers,vehicles=[],services,staff=[],resources=[],error,customerQ,requiresVehicle=true,customerLabel="Customer",serviceLabel="Service",resourceLabel="Service bay",idPrefix}:{mode:"appointment"|"walk_in";action:(data:FormData)=>void|Promise<void>;appointment?:{id:string;branch_id:string;customer_id:string;vehicle_id:string|null;starts_at:string;customer_note:string|null;internal_note:string|null;serviceIds:string[];staffIds?:string[];resourceIds?:string[]};defaults?:{customerId?:string;vehicleId?:string;serviceId?:string;branchId?:string;maintenanceDueId?:string};branches:Choice[];customers:Choice[];vehicles?:VehicleChoice[];services:ServiceChoice[];staff?:StaffChoice[];resources?:ResourceChoice[];error?:string;customerQ?:string;requiresVehicle?:boolean;customerLabel?:string;serviceLabel?:string;resourceLabel?:string;idPrefix?:string}) {
  const controlPrefix=idPrefix??mode,formId=idPrefix?`${idPrefix}-${appointment?"edit":"create"}-form`:mode==="walk_in"?"walk-in-create-form":appointment?"appointment-edit-form":"appointment-create-form";
  return <><form id={`${controlPrefix}-customer-search-form`} className="mb-4 flex gap-2">{defaults?.maintenanceDueId?<input type="hidden" name="maintenanceDueId" value={defaults.maintenanceDueId}/>:null}<input id={`${controlPrefix}-customer-search-input`} className="min-h-11 grow rounded-xl border border-zinc-200 bg-white px-3 text-zinc-950" name="customerQ" defaultValue={customerQ} placeholder={`Find ${customerLabel.toLowerCase()} by name, phone, or email`}/><button id={`${controlPrefix}-customer-search-button`} className="min-h-11 rounded-xl border border-zinc-200 bg-white px-4 font-bold" type="submit">Find</button></form><Card className="p-5 sm:p-7"><FormMessage error={error}/><form id={formId} action={action} className="mt-5 grid gap-5 sm:grid-cols-2">
    {appointment&&<input type="hidden" name="appointmentId" value={appointment.id}/>} {defaults?.maintenanceDueId?<input type="hidden" name="maintenanceDueId" value={defaults.maintenanceDueId}/>:null}<Field label="Branch *"><select id={`${controlPrefix}-branch-select`} className={select} required name="branchId" defaultValue={appointment?.branch_id??defaults?.branchId??branches[0]?.id}>{branches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></Field>
    <Field label={customerLabel}><select id={`${controlPrefix}-${customerLabel.toLowerCase()}-select`} className={select} name="customerId" defaultValue={appointment?.customer_id??defaults?.customerId??""}><option value="">Create or select {customerLabel.toLowerCase()}</option>{customers.map(customer=><option key={customer.id} value={customer.id}>{customer.name}</option>)}</select><details id={`${controlPrefix}-quick-${customerLabel.toLowerCase()}-details`} className="mt-3 rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer text-xs font-bold text-brand-primary-strong">+ Create {customerLabel.toLowerCase()} here</summary><div className="mt-3 grid gap-2"><Input id={`${controlPrefix}-quick-${customerLabel.toLowerCase()}-name`} name="quickCustomerName" placeholder="Full name"/><Input id={`${controlPrefix}-quick-${customerLabel.toLowerCase()}-phone`} name="quickCustomerPhone" placeholder="Phone (optional)"/><Input id={`${controlPrefix}-quick-${customerLabel.toLowerCase()}-email`} name="quickCustomerEmail" type="email" placeholder="Email (optional)"/></div></details></Field>
    {requiresVehicle?<Field label="Vehicle *"><select id={`${mode}-vehicle-select`} className={select} required name="vehicleId" defaultValue={appointment?.vehicle_id??defaults?.vehicleId??""}><option value="">Create or select vehicle</option>{vehicles.map(vehicle=><option key={vehicle.id} value={vehicle.id}>{vehicle.label}</option>)}</select><details className="mt-3 rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer text-xs font-bold text-brand-primary-strong">+ Create vehicle here</summary><div className="mt-3 grid gap-2"><Input name="quickVehicleMake" placeholder="Make"/><Input name="quickVehicleModel" placeholder="Model"/><Input name="quickVehiclePlate" placeholder="Plate (optional)"/><Input name="quickVehicleType" placeholder="Vehicle class, e.g. SUV"/></div></details></Field>:null}
    {mode==="appointment"&&<><Field label="Date and time *"><Input id={`${controlPrefix}-starts-at-input`} required type="datetime-local" name="startsAt" defaultValue={appointment?.starts_at}/></Field><label className="flex min-h-11 items-center gap-2 text-sm font-semibold"><input id={`${controlPrefix}-allow-conflict-checkbox`} type="checkbox" name="acceptConflict"/> Allow an overlapping booking after reviewing the schedule</label></>}
    {mode==="appointment"&&<><Field label="Assigned staff"><select id={`${controlPrefix}-staff-select`} className={select} name="staffIds" defaultValue={appointment?.staffIds?.[0]??""}><option value="">Unassigned</option>{staff.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></Field><Field label={resourceLabel}><select id={`${controlPrefix}-resource-select`} className={select} name="resourceIds" defaultValue={appointment?.resourceIds?.[0]??""}><option value="">Unassigned</option>{resources.map(resource=><option key={resource.id} value={resource.id}>{resource.name}{resource.capacity>1?` · capacity ${resource.capacity}`:""}</option>)}</select></Field></>}
    <fieldset id={`${controlPrefix}-services-fieldset`} className="sm:col-span-2"><legend className="text-sm font-semibold">{serviceLabel}s *</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{services.map(service=><label className="flex min-h-14 items-center gap-3 rounded-xl border border-zinc-200 p-3" key={service.id}><input id={`${controlPrefix}-service-${service.id}`} type="checkbox" name="serviceIds" value={service.id} defaultChecked={appointment?.serviceIds.includes(service.id)||defaults?.serviceId===service.id}/><span><span className="block font-bold">{service.name}</span><span className="text-xs text-zinc-500">From {formatMoney(service.base_price_centavos)} · {formatDuration(service.duration_minutes)}</span></span></label>)}</div><p className="mt-2 text-xs text-zinc-500">The database resolves final estimates. Restricted add-ons require their compatible parent service.</p></fieldset>
    <div className="sm:col-span-2"><Field label={mode==="appointment"?`${customerLabel} notes`:"Walk-in notes"}><textarea id={`${controlPrefix}-customer-notes-input`} className={textarea} name={mode==="appointment"?"customerNote":"notes"} defaultValue={appointment?.customer_note??""}/></Field></div>
    {mode==="appointment"&&<div className="sm:col-span-2"><Field label="Internal notes"><textarea id={`${controlPrefix}-internal-notes-input`} className={textarea} name="internalNote" defaultValue={appointment?.internal_note??""}/></Field></div>}
    <div className="sm:col-span-2"><SubmitButton id={`${controlPrefix}-save-button`} pendingText="Saving…">{mode==="appointment"?"Book appointment":"Add to queue"}</SubmitButton></div>
  </form></Card></>;
}
