import Link from "next/link";
import { transitionQueue } from "@/app/dashboard/operations-actions";
import { FormMessage } from "@/components/form-message";
import { SubmitButton } from "@/components/submit-button";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { getDashboardContext } from "@/lib/auth/context";
import { formatDuration,formatMoney,queueLabel } from "@/lib/operations";
import { createClient } from "@/lib/supabase/server";

export default async function Page({searchParams}:{searchParams:Promise<{q?:string;message?:string;error?:string}>}) {
  const [params,{activeMembership},supabase]=await Promise.all([searchParams,getDashboardContext(),createClient()]),today=new Intl.DateTimeFormat("en-CA",{timeZone:activeMembership.timezone}).format(new Date()),search=params.q?.trim().slice(0,100);
  let directory=supabase.from("queue_directory").select("id").eq("organization_id",activeMembership.organizationId).eq("branch_id",activeMembership.branchId).eq("queue_date",today).order("queue_number"); if(search) directory=directory.ilike("search_document",`%${search.replace(/[,%()]/g," ")}%`);
  const {data:matches,error:searchError}=await directory,ids=matches?.map(match=>match.id)??[];
  const {data,error}=ids.length?await supabase.from("queue_entries").select("id,source,queue_number,status,checked_in_at,estimated_total_centavos,estimated_duration_minutes,customers(full_name),vehicles(make,model,plate_number),appointments(appointment_services(service_name_snapshot))").in("id",ids):{data:[],error:null};
  const byId=new Map(data?.map(row=>[row.id,row])),entries=ids.map(id=>byId.get(id)).filter((row):row is NonNullable<typeof row>=>Boolean(row)),canWrite=["owner","manager","advisor"].includes(activeMembership.role),active=entries.filter(entry=>!["cancelled","converted_to_job"].includes(entry.status));
  return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-amber-700">{activeMembership.branchName}</p><h1 className="mt-1 text-3xl font-black">Today&apos;s Queue</h1><p className="mt-2 text-zinc-600">{active.length} vehicle{active.length===1?"":"s"} waiting or called.</p></div>{canWrite&&<Button asChild><Link href="/dashboard/queue/new">Add walk-in</Link></Button>}</div><FormMessage message={params.message} error={params.error??(searchError||error?"Unable to load the queue.":undefined)}/>
    <form className="mt-6 flex gap-2"><input className="min-h-11 grow rounded-xl border border-zinc-200 bg-white px-3 text-zinc-950" name="q" defaultValue={params.q} placeholder="Queue number, customer, plate, or vehicle"/><Button type="submit" variant="secondary">Search</Button></form>
    <div className="mt-6 grid gap-4 md:grid-cols-2">{entries.map(entry=>{const customer=Array.isArray(entry.customers)?entry.customers[0]:entry.customers,vehicle=Array.isArray(entry.vehicles)?entry.vehicles[0]:entry.vehicles,appointment=Array.isArray(entry.appointments)?entry.appointments[0]:entry.appointments;return <Card className="p-5" key={entry.id}><div className="flex items-start justify-between gap-3"><div><p className="text-2xl font-black text-amber-800">{queueLabel(entry.source as "appointment"|"walk_in",entry.queue_number)}</p><span className="text-xs font-bold capitalize text-zinc-500">{entry.source.replaceAll("_"," ")}</span></div><span className="rounded-full bg-zinc-100 px-3 py-1 text-xs font-bold capitalize">{entry.status.replaceAll("_"," ")}</span></div><h2 className="mt-4 text-lg font-black">{vehicle?.make} {vehicle?.model}{vehicle?.plate_number?` · ${vehicle.plate_number}`:""}</h2><p className="text-sm text-zinc-600">{customer?.full_name}</p><p className="mt-2 text-sm">{appointment?.appointment_services.map(service=>service.service_name_snapshot).join(", ")}</p><div className="mt-3 flex flex-wrap justify-between gap-2 text-xs text-zinc-500"><span>{formatDuration(entry.estimated_duration_minutes)}</span><span>{formatMoney(entry.estimated_total_centavos)}</span><span>Arrived {new Intl.DateTimeFormat("en-PH",{timeZone:activeMembership.timezone,timeStyle:"short"}).format(new Date(entry.checked_in_at))}</span></div>{canWrite&&<div className="mt-5 flex flex-wrap gap-2">{entry.status==="waiting"&&<QueueAction id={entry.id} status="called" label="Call vehicle"/>}{entry.status==="called"&&<QueueAction id={entry.id} status="ready" label="Mark ready"/>}{["waiting","called"].includes(entry.status)&&<QueueAction id={entry.id} status="cancelled" label="Cancel" destructive/>}{entry.status==="ready"&&<Button disabled>Start job — Phase 05</Button>}</div>}</Card>})}{!searchError&&!error&&entries.length===0&&<Card className="p-10 text-center md:col-span-2"><h2 className="font-black">No matching vehicles</h2><p className="mt-2 text-sm text-zinc-600">Add a walk-in, mark an appointment as arrived, or clear the search.</p></Card>}</div>
  </div>;
}
function QueueAction({id,status,label,destructive}:{id:string;status:string;label:string;destructive?:boolean}) { return <form action={transitionQueue}><input type="hidden" name="id" value={id}/><input type="hidden" name="status" value={status}/><SubmitButton pendingText="Updating…" variant={destructive?"destructive":"secondary"}>{label}</SubmitButton></form>; }
