import Link from "next/link";
import { notFound } from "next/navigation";
import { randomUUID } from "node:crypto";

import { enqueueAppointment, transitionAppointment } from "@/app/dashboard/operations-actions";
import { createSalonAppointmentLink,recordSalonAppointmentPayment,transitionSalonAppointment } from "@/app/dashboard/appointments/salon-actions";
import { FormMessage } from "@/components/form-message";
import { FormDialog } from "@/components/management-ui";
import { SubmitButton } from "@/components/submit-button";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { getDashboardContext } from "@/lib/auth/context";
import { formatDuration, formatMoney } from "@/lib/operations";
import { createClient } from "@/lib/supabase/server";
import { assignmentContextLabel, loadAppointmentAssignmentContext } from "@/modules/core/scheduling/appointment-assignment-view";
import { calculateAppointmentPaymentSummary,paymentMethods } from "@/modules/core/payments/payment.service";
import { verticalBrands } from "@/modules/platform/brand";
import { resolveIndustryConfig } from "@/modules/platform/industry";
import { salonAppointmentActions,salonAppointmentActionLabels,type SalonAppointmentAction } from "@/modules/salon/appointments";

type AppointmentDetail={id:string;vehicle_id?:string|null;status:string;source:string;starts_at:string|null;ends_at:string|null;expected_total_centavos:number;expected_duration_minutes:number|null;customer_note:string|null;internal_note:string|null;cancellation_reason:string|null;created_at:string;branches:{name:string;timezone:string}|{name:string;timezone:string}[]|null;customers:{id:string;full_name:string;phone:string|null}|{id:string;full_name:string;phone:string|null}[]|null;vehicles?:{id:string;make:string|null;model:string|null;plate_number:string|null}|{id:string;make:string|null;model:string|null;plate_number:string|null}[]|null;appointment_services:Array<{service_id:string;service_name_snapshot:string;unit_price_centavos:number;duration_minutes:number}>};

export default async function Page({ params, searchParams }: { params: Promise<{ appointmentId: string }>; searchParams: Promise<{ message?: string; error?: string;dialog?:string;customerLink?:string }> }) {
  const [{ appointmentId }, query, { activeMembership }, supabase] = await Promise.all([params, searchParams, getDashboardContext(), createClient()]);
  const config=resolveIndustryConfig(activeMembership.industry),salon=config.key==="salon";
  const appointmentResult = salon
    ? await supabase.from("appointments").select("id,status,source,starts_at,ends_at,expected_total_centavos,expected_duration_minutes,customer_note,internal_note,cancellation_reason,created_at,branches(name,timezone),customers(id,full_name,phone),appointment_services(service_id,service_name_snapshot,unit_price_centavos,duration_minutes)").eq("id", appointmentId).eq("organization_id", activeMembership.organizationId).maybeSingle()
    : await supabase.from("appointments").select("id,vehicle_id,status,source,starts_at,ends_at,expected_total_centavos,expected_duration_minutes,customer_note,internal_note,cancellation_reason,created_at,branches(name,timezone),customers(id,full_name,phone),vehicles(id,make,model,plate_number),appointment_services(service_id,service_name_snapshot,unit_price_centavos,duration_minutes)").eq("id", appointmentId).eq("organization_id", activeMembership.organizationId).maybeSingle();
  const appointment = appointmentResult.data as unknown as AppointmentDetail|null;
  if (!appointment) notFound();
  const assignmentContext = await loadAppointmentAssignmentContext(activeMembership.organizationId, [appointment.id]);
  const assignmentLabels = assignmentContextLabel(assignmentContext.get(appointment.id) ?? { scheduledStaff: [], scheduledResources: [] });

  const branch = Array.isArray(appointment.branches) ? appointment.branches[0] : appointment.branches;
  const customer = Array.isArray(appointment.customers) ? appointment.customers[0] : appointment.customers;
  const vehicle = Array.isArray(appointment.vehicles) ? appointment.vehicles[0] : appointment.vehicles;
  const canWrite = ["owner", "manager", "advisor"].includes(activeMembership.role);
  const canPay=["owner","manager","cashier"].includes(activeMembership.role);
  const editable = ["requested", "confirmed"].includes(appointment.status);
  const canEnterAutomotiveQueue = ["checked_in", "confirmed"].includes(appointment.status);
  const vehicleName=vehicle?[vehicle.make,vehicle.model,vehicle.plate_number&&`(${vehicle.plate_number})`].filter(Boolean).join(" "):"Vehicle not assigned";
  const[{data:paymentRows},{data:activeLink}]=salon?await Promise.all([
    supabase.from("payments").select("id,amount_centavos,status,method,reference,paid_at").eq("organization_id",activeMembership.organizationId).eq("appointment_id",appointment.id).order("paid_at",{ascending:false}),
    supabase.from("appointment_self_service_links").select("id,status,expires_at").eq("appointment_id",appointment.id).eq("status","active").maybeSingle(),
  ]):[{data:[]},{data:null}];
  const payment=calculateAppointmentPaymentSummary(appointment.expected_total_centavos,(paymentRows??[]).map(row=>({amountCentavos:Number(row.amount_centavos),status:row.status})));
  const salonActions=salon?salonAppointmentActions(appointment.status):[];

  return <div id={salon?"salon-appointment-details":"appointment-details-page"} className="mx-auto max-w-5xl">
    <div id="appointment-details-header" className="flex flex-wrap justify-between gap-4">
      <div><p className="text-sm font-bold capitalize text-brand-primary">{appointment.source.replaceAll("_", " ")} · {appointment.status.replaceAll("_", " ")}</p><h1 id={salon?"salon-appointment-client":"appointment-vehicle-value"} className="mt-1 text-3xl font-black">{salon?customer?.full_name:vehicleName}</h1><p className="mt-2 text-zinc-600">{salon?appointment.appointment_services.map(item=>item.service_name_snapshot).join(", "):`${customer?.full_name} · ${branch?.name}`}</p></div>
      {canWrite && editable && <Button asChild variant="secondary"><Link id={salon?"salon-appointment-edit-button":"appointment-edit-button"} href={`/dashboard/appointments/${appointment.id}/edit`}>Edit</Link></Button>}
    </div>
    <FormMessage {...query}/>
    <Card id="appointment-scheduling-assignment-context" className="mt-6 p-5"><h2 className="font-black">Scheduling assignments</h2><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-zinc-500">Scheduled Staff</dt><dd className="font-semibold">{assignmentLabels.staff}</dd></div><div><dt className="text-zinc-500">{config.terminology.resource}</dt><dd className="font-semibold">{assignmentLabels.resources}</dd></div></dl></Card>
    <div className="mt-6 grid gap-5 lg:grid-cols-[1.3fr_1fr]">
      <Card className="p-5"><h2 className="font-black">Visit details</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-zinc-500">Schedule</dt><dd className="font-bold">{new Intl.DateTimeFormat("en-PH", { timeZone: branch?.timezone ?? activeMembership.timezone, dateStyle: "medium", timeStyle: "short" }).format(new Date(appointment.starts_at!))}</dd></div><div><dt className="text-zinc-500">Estimated duration</dt><dd className="font-bold">{appointment.expected_duration_minutes ? formatDuration(appointment.expected_duration_minutes) : "—"}</dd></div><div><dt className="text-zinc-500">{salon?"Client notes":"Customer notes"}</dt><dd>{appointment.customer_note || "None"}</dd></div><div><dt className="text-zinc-500">Internal notes</dt><dd>{appointment.internal_note || "None"}</dd></div></dl><h3 className="mt-6 font-black">{salon?"Treatments":"Services"}</h3><div className="mt-2 space-y-2">{appointment.appointment_services.map((item) => <div className="flex justify-between gap-3 border-b border-zinc-100 py-2 text-sm" key={item.service_id}><span>{item.service_name_snapshot}<span className="block text-xs text-zinc-500">{formatDuration(item.duration_minutes)}</span></span><strong>{formatMoney(item.unit_price_centavos)}</strong></div>)}<div className="flex justify-between pt-2 font-black"><span>Estimated Total</span><span>{formatMoney(appointment.expected_total_centavos)}</span></div></div></Card>
      <div className="grid h-fit gap-5"><Card className="p-5"><h2 className="font-black">Actions</h2>{canWrite && <div className="mt-4 grid gap-3">{salon?salonActions.map(action=><SalonAction key={action} id={appointment.id} action={action}/>):<>{appointment.status === "requested" && <Action id={appointment.id} action="confirm" label="Confirm appointment"/>}{["requested", "confirmed"].includes(appointment.status) && <Action id={appointment.id} action="arrive" label="Mark arrived"/>}{["requested", "confirmed"].includes(appointment.status) && <Action id={appointment.id} action="no_show" label="Mark no-show" destructive/>}{["requested", "confirmed"].includes(appointment.status) && <Action id={appointment.id} action="cancel" label="Cancel appointment" destructive/>}{canEnterAutomotiveQueue && appointment.vehicle_id && <form id="appointment-enqueue-form" action={enqueueAppointment}><input type="hidden" name="id" value={appointment.id}/><SubmitButton id="appointment-enqueue-button" pendingText="Adding…">Add to queue</SubmitButton></form>}{canEnterAutomotiveQueue && !appointment.vehicle_id && <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Assign a vehicle before adding this appointment to the {verticalBrands.automotive.displayName} queue.</p>}{appointment.status === "queued" && <Button asChild><Link href="/dashboard/queue">View in queue</Link></Button>}</>}</div>}{!salon?<p className="mt-5 text-xs text-zinc-500">{verticalBrands.automotive.displayName} queue and Job Order workflows require a vehicle.</p>:null}</Card>
      {salon&&<Card id="salon-appointment-customer-self-service" className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black">Customer self-service</h2><p className="mt-1 text-xs text-zinc-500">Private confirmation and reschedule link.</p></div>{canWrite&&editable?<form action={createSalonAppointmentLink}><input type="hidden" name="id" value={appointment.id}/><SubmitButton id="salon-appointment-create-customer-link-button" size="sm" pendingText="Creating…">{activeLink?"Replace link":"Create link"}</SubmitButton></form>:null}</div>{query.customerLink?<code id="salon-appointment-customer-link" className="mt-3 block break-all rounded-lg border border-brand-border bg-brand-tint p-3 text-xs">{query.customerLink}</code>:activeLink?<p className="mt-3 text-sm text-emerald-700">Active until {new Intl.DateTimeFormat("en-PH",{dateStyle:"medium",timeStyle:"short",timeZone:branch?.timezone??activeMembership.timezone}).format(new Date(activeLink.expires_at))}. Reminders use the shared outbox.</p>:<p className="mt-3 text-sm text-zinc-500">No active customer link.</p>}</Card>}
      {salon&&<Card id="salon-appointment-payment-summary" className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-black">Payment</h2>{canPay&&payment.balanceCentavos>0?<Button id="salon-appointment-record-payment-button" asChild size="sm"><Link href={`/dashboard/appointments/${appointment.id}?dialog=payment`}>Record payment</Link></Button>:null}</div><dl className="mt-3 grid grid-cols-3 gap-2 rounded-xl bg-zinc-50 p-3 text-sm"><div><dt>Total</dt><dd className="font-black">{formatMoney(payment.totalCentavos)}</dd></div><div><dt>Paid</dt><dd className="font-black text-emerald-700">{formatMoney(payment.paidCentavos)}</dd></div><div><dt>Balance</dt><dd className="font-black text-red-700">{formatMoney(payment.balanceCentavos)}</dd></div></dl><p className="mt-2 text-xs font-bold uppercase text-zinc-500">{payment.status}</p>{paymentRows?.length?<div className="mt-3 divide-y">{paymentRows.map(row=><div id={`salon-appointment-payment-${row.id}`} key={row.id} className="flex justify-between py-2 text-sm"><span className="capitalize">{row.method.replaceAll("_"," ")}<small className="block text-zinc-500">{row.reference||row.status}</small></span><strong>{formatMoney(row.amount_centavos)}</strong></div>)}</div>:null}</Card>}</div>
    </div>
    {salon&&canPay&&query.dialog==="payment"&&payment.balanceCentavos>0?<FormDialog id="salon-appointment-payment-dialog" title="Record payment" description="Record an externally received payment. No online charge is initiated." closeHref={`/dashboard/appointments/${appointment.id}`} size="md"><form id="salon-appointment-payment-form" action={recordSalonAppointmentPayment} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="appointmentId" value={appointment.id}/><input type="hidden" name="idempotencyKey" value={randomUUID()}/><label className="text-sm font-semibold">Amount PHP<Input id="salon-appointment-payment-amount-input" name="amount" required inputMode="decimal" defaultValue={(payment.balanceCentavos/100).toFixed(2)} max={(payment.balanceCentavos/100).toFixed(2)}/></label><label className="text-sm font-semibold">Method<select id="salon-appointment-payment-method-select" name="method" className="mt-2 min-h-11 w-full rounded-xl border bg-white px-3">{paymentMethods.map(method=><option value={method} key={method}>{method.replaceAll("_"," ")}</option>)}</select></label><label className="text-sm font-semibold">Reference<Input id="salon-appointment-payment-reference-input" name="reference" maxLength={100}/></label><label className="text-sm font-semibold">Notes<Input id="salon-appointment-payment-notes-input" name="notes" maxLength={1000}/></label><div className="flex justify-end gap-2 sm:col-span-2"><Button asChild variant="secondary"><Link href={`/dashboard/appointments/${appointment.id}`}>Cancel</Link></Button><SubmitButton id="salon-appointment-payment-save-button" pendingText="Recording…">Record payment</SubmitButton></div></form></FormDialog>:null}
  </div>;
}

function Action({ id, action, label, destructive }: { id: string; action: string; label: string; destructive?: boolean }) {
  return <form id={`appointment-${action}-form`} action={transitionAppointment}><input type="hidden" name="id" value={id}/><input type="hidden" name="action" value={action}/><SubmitButton id={`appointment-${action}-button`} pendingText="Updating…" variant={destructive ? "destructive" : "secondary"}>{label}</SubmitButton></form>;
}

function SalonAction({id,action}:{id:string;action:SalonAppointmentAction}){const destructive=action==="cancel"||action==="no_show";return <form id={`salon-appointment-${action}-form`} action={transitionSalonAppointment}><input type="hidden" name="id" value={id}/><input type="hidden" name="action" value={action}/><SubmitButton id={`salon-appointment-${action.replaceAll("_","-")}-button`} pendingText="Updating…" variant={destructive?"destructive":"secondary"}>{salonAppointmentActionLabels[action]}</SubmitButton></form>}
