import Link from "next/link";
import { notFound } from "next/navigation";
import { addJobService, assignJobItem, transitionJobService } from "@/app/dashboard/job-actions";
import { FormMessage } from "@/components/form-message";
import { SubmitButton } from "@/components/submit-button";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { getDashboardContext } from "@/lib/auth/context";
import { formatMoney } from "@/lib/operations";
import { createClient } from "@/lib/supabase/server";

export default async function Page({params,searchParams}:{params:Promise<{jobId:string}>;searchParams:Promise<{message?:string;error?:string}>}) {
  const [{jobId},query,{activeMembership},supabase]=await Promise.all([params,searchParams,getDashboardContext(),createClient()]);
  const [{data:job},{data:services},{data:members}]=await Promise.all([
    supabase.from("job_orders").select("id,branch_id,status,job_order_items(id,service_name_snapshot,quantity,line_total_centavos,approval_status,notes,technician_staff_id,technician_assigned_at)").eq("id",jobId).eq("organization_id",activeMembership.organizationId).maybeSingle(),
    supabase.from("services").select("id,name,base_price_centavos").eq("organization_id",activeMembership.organizationId).eq("is_active",true).order("name"),
    supabase.from("staff_directory").select("staff_id,full_name,branch_ids").eq("organization_id",activeMembership.organizationId).eq("is_active",true),
  ]);
  if(!job) notFound();
  const canManage=["owner","manager","advisor"].includes(activeMembership.role);
  const branchStaff=(members??[]).filter(staff=>!staff.branch_ids.length||staff.branch_ids.includes(job.branch_id));
  return <div className="mx-auto max-w-3xl"><div className="flex justify-between gap-3"><div><p className="text-sm font-bold text-brand-primary">Job order</p><h1 className="text-3xl font-black">Work and approvals</h1></div><Button asChild variant="secondary"><Link href={`/dashboard/jobs/${job.id}`}>Back to job</Link></Button></div><FormMessage {...query}/><Card className="mt-6 p-5"><h2 className="font-black">Current work</h2><div className="mt-3 space-y-3">{job.job_order_items.map(item=><div className="rounded-xl border p-3" key={item.id}><div className="flex justify-between gap-3"><span><strong>{item.service_name_snapshot} × {item.quantity}</strong><small className="block capitalize text-zinc-500">{item.approval_status}</small></span><strong>{formatMoney(item.line_total_centavos)}</strong></div>{item.notes&&<p className="mt-2 text-sm">{item.notes}</p>}{canManage&&<form action={assignJobItem} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="jobId" value={job.id}/><input type="hidden" name="itemId" value={item.id}/><select aria-label={`Technician for ${item.service_name_snapshot}`} name="staffId" defaultValue={item.technician_staff_id??""} className="min-h-10 grow rounded-xl border bg-white px-3 text-sm"><option value="">No service technician</option>{branchStaff.map(staff=><option key={staff.staff_id} value={staff.staff_id}>{staff.full_name}</option>)}</select><SubmitButton pendingText="Assigning…" variant="secondary">Assign</SubmitButton></form>}{canManage&&item.approval_status==="proposed"&&<div className="mt-3 flex gap-2"><ItemAction jobId={job.id} itemId={item.id} action="approve"/><ItemAction jobId={job.id} itemId={item.id} action="decline"/></div>}</div>)}</div></Card>{canManage&&!['completed','cancelled'].includes(job.status)&&<Card className="mt-5 p-5"><h2 className="font-black">Add additional work</h2><form action={addJobService} className="mt-4 grid gap-4"><input type="hidden" name="jobId" value={job.id}/><label className="text-sm font-semibold">Service<select required name="serviceId" className="mt-2 min-h-11 w-full rounded-xl border bg-white px-3"><option value="">Select service</option>{services?.map(service=><option key={service.id} value={service.id}>{service.name} · {formatMoney(service.base_price_centavos)}</option>)}</select></label><label className="text-sm font-semibold">Quantity<Input required name="quantity" type="number" min={1} max={100} defaultValue={1}/></label><label className="flex items-center gap-2 text-sm font-semibold"><input name="requiresApproval" type="checkbox" defaultChecked/> Customer approval required</label><label className="text-sm font-semibold">Notes<textarea name="notes" className="mt-2 min-h-20 w-full rounded-xl border bg-white px-3 py-2"/></label><SubmitButton pendingText="Adding…">Add work</SubmitButton></form></Card>}</div>;
}
function ItemAction({jobId,itemId,action}:{jobId:string;itemId:string;action:"approve"|"decline"}) { return <form action={transitionJobService}><input type="hidden" name="jobId" value={jobId}/><input type="hidden" name="itemId" value={itemId}/><input type="hidden" name="action" value={action}/><SubmitButton pendingText="Updating…" variant={action==="decline"?"destructive":"secondary"}>{action==="approve"?"Approve":"Decline"}</SubmitButton></form>; }
