import Link from "next/link";
import { saveCategory,toggleCategory } from "@/app/dashboard/operations-actions";
import { FormMessage } from "@/components/form-message";
import { FilterBar, PageHeader } from "@/components/page-patterns";
import { SubmitButton } from "@/components/submit-button";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { getDashboardContext } from "@/lib/auth/context";
import { formatDuration,formatMoney } from "@/lib/operations";
import { createClient } from "@/lib/supabase/server";
import { resolveIndustryConfig } from "@/modules/platform/industry";

type ServiceRow={id:string;name:string;short_description:string|null;duration_minutes:number;base_price_centavos:number;is_active:boolean;is_add_on:boolean;service_categories:{name:string}|{name:string}[]|null;service_branch_availability?:Array<{is_available:boolean;branches:{name:string}|{name:string}[]|null}>};
const categoryName=(service:ServiceRow)=>{const category=Array.isArray(service.service_categories)?service.service_categories[0]:service.service_categories;return category?.name??"Uncategorized";};
const availabilityLabel=(service:ServiceRow)=>{const names=(service.service_branch_availability??[]).filter(row=>row.is_available).map(row=>{const branch=Array.isArray(row.branches)?row.branches[0]:row.branches;return branch?.name;}).filter(Boolean);return names.length?names.join(", "):"All active branches";};

export default async function Page({searchParams}:{searchParams:Promise<{q?:string;category?:string;message?:string;error?:string}>}) {
  const [params,{activeMembership},supabase]=await Promise.all([searchParams,getDashboardContext(),createClient()]),search=params.q?.trim().replace(/[,%()]/g," ").slice(0,100);
  const config=resolveIndustryConfig(activeMembership.industry),salon=config.key==="salon";
  let serviceQuery=supabase.from("services").select("id,name,short_description,duration_minutes,base_price_centavos,is_active,is_add_on,service_categories(name),service_branch_availability(is_available,branches(name))").eq("organization_id",activeMembership.organizationId).order("name");
  if(search) serviceQuery=serviceQuery.ilike("name",`%${search}%`);
  if(params.category) serviceQuery=serviceQuery.eq("category_id",params.category);
  const [{data:serviceData,error},{data:categories}]=await Promise.all([serviceQuery,supabase.from("service_categories").select("id,name,sort_order,is_active").eq("organization_id",activeMembership.organizationId).order("sort_order").order("name")]);
  const services=(serviceData??[]) as unknown as ServiceRow[],canManage=["owner","manager"].includes(activeMembership.role);
  return <main id={salon?"salon-treatments-page":"services-page"} className="mx-auto min-w-0 max-w-7xl"><PageHeader id={salon?"salon-treatments-page-header":"services-page-header"} eyebrow="Catalog and pricing" title={`${config.terminology.service}s`} description={`Define what your ${salon?"salon":"shop"} offers, estimated duration, and trusted prices.`} action={canManage?<Button asChild><Link id={salon?"salon-treatment-create-button":"service-create-button"} href="/dashboard/services/new">Add {config.terminology.service.toLowerCase()}</Link></Button>:undefined}/><FormMessage message={params.message} error={params.error??(error?`Unable to load ${config.terminology.service.toLowerCase()}s.`:undefined)}/>
    <FilterBar id={salon?"salon-treatments-filter-bar":"services-filter-bar"}><form id={salon?"salon-treatments-filter-form":"services-filter-form"} className="grid gap-2 sm:grid-cols-[1fr_220px_auto]"><Input id={salon?"salon-treatments-search-input":"services-search-input"} aria-label={`Search ${config.terminology.service.toLowerCase()}s`} name="q" defaultValue={params.q} placeholder={`Search ${config.terminology.service.toLowerCase()} name`}/><select id={salon?"salon-treatments-category-filter":"services-category-filter"} aria-label={`${config.terminology.service} category`} className="min-h-11 rounded-xl border border-zinc-200 bg-white px-3" name="category" defaultValue={params.category??""}><option value="">All categories</option>{categories?.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select><Button id={salon?"salon-treatments-filter-button":"services-filter-button"} type="submit" variant="secondary">Search</Button></form></FilterBar>
    <div className="mt-5 grid min-w-0 gap-4 xl:grid-cols-[240px_minmax(0,1fr)]"><CategoryPanel categories={categories ?? []} canManage={canManage} salon={salon}/>
      {salon?<SalonTreatmentViews services={services}/>:<div className="grid gap-3">{services.map(service=><TreatmentCard key={service.id} service={service}/>)}{services.length===0&&<EmptyServices label="service"/>}</div>}
    </div>
  </main>;
}

function SalonTreatmentViews({services}:{services:ServiceRow[]}) { return <div className="min-w-0"><div id="salon-treatments-table-container" className="hidden overflow-hidden rounded-ui-lg border border-zinc-200 bg-white shadow-ui-sm xl:block"><table id="salon-treatments-table" className="w-full text-left text-sm"><thead className="bg-zinc-50 text-xs uppercase tracking-wide text-zinc-500"><tr><th className="px-3 py-3">Treatment</th><th className="px-3 py-3">Category</th><th className="px-3 py-3">Duration</th><th className="px-3 py-3">Price</th><th className="px-3 py-3">Branches</th><th className="px-3 py-3">Status</th><th className="px-3 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-zinc-100">{services.map(service=><tr id={`salon-treatment-row-${service.id}`} key={service.id}><td className="px-3 py-3"><strong>{service.name}</strong>{service.short_description&&<small className="block max-w-48 truncate text-zinc-500">{service.short_description}</small>}</td><td className="px-3 py-3">{categoryName(service)}</td><td className="px-3 py-3">{formatDuration(service.duration_minutes)}</td><td className="px-3 py-3 font-bold">{formatMoney(service.base_price_centavos)}</td><td className="max-w-40 px-3 py-3 text-xs">{availabilityLabel(service)}</td><td className="px-3 py-3">{service.is_active?"Active":"Inactive"}</td><td className="px-3 py-3 text-right"><Link id={`salon-treatment-view-${service.id}`} className="font-bold text-brand-primary-strong" href={`/dashboard/services/${service.id}`}>View</Link></td></tr>)}</tbody></table></div><div id="salon-treatments-mobile-list" className="grid gap-3 xl:hidden">{services.map(service=><TreatmentCard key={service.id} service={service} salon/>)}</div>{services.length===0&&<EmptyServices label="treatment"/>}</div>; }

type CategoryRow={id:string;name:string;sort_order:number;is_active:boolean};
function CategoryPanel({categories,canManage,salon}:{categories:CategoryRow[];canManage:boolean;salon:boolean}) { const prefix=salon?"salon-treatment-category":"service-category"; return <Card id={`${prefix}-panel`} elevation="none" className="h-fit p-5"><h2 className="font-semibold">Categories</h2><p className="mt-1 text-xs text-zinc-500">Edit names and sort order directly.</p><div className="mt-3 space-y-3">{categories.map(category=><div id={`${prefix}-${category.id}`} key={category.id} className="rounded-xl border border-zinc-200 p-3">{canManage?<><form id={`${prefix}-edit-form-${category.id}`} action={saveCategory} className="grid min-w-0 gap-2"><input type="hidden" name="id" value={category.id}/><label className="text-xs font-semibold text-slate-600">Category name<Input id={`${prefix}-name-input-${category.id}`} required name="name" maxLength={100} defaultValue={category.name}/></label><label className="text-xs font-semibold text-slate-600">Sort order<Input id={`${prefix}-sort-input-${category.id}`} required type="number" min={0} max={9999} name="sortOrder" defaultValue={category.sort_order}/></label><SubmitButton id={`${prefix}-save-button-${category.id}`} pendingText="Saving category…" variant="secondary">Save</SubmitButton></form><form id={`${prefix}-toggle-form-${category.id}`} action={toggleCategory} className="mt-2"><input type="hidden" name="id" value={category.id}/><input type="hidden" name="active" value={String(!category.is_active)}/><SubmitButton id={`${prefix}-toggle-button-${category.id}`} pendingText="Updating category…" variant="secondary">{category.is_active?"Deactivate":"Activate"}</SubmitButton></form></>:<span className={!category.is_active?"text-zinc-400":"font-semibold"}>{category.name}</span>}</div>)}</div>{canManage?<form id={`${prefix}-create-form`} action={saveCategory} className="mt-5 border-t border-zinc-200 pt-4"><label className="text-sm font-semibold">New category<Input id={`${prefix}-create-name-input`} required name="name" maxLength={100}/></label><input type="hidden" name="sortOrder" value={categories.length}/><SubmitButton id={`${prefix}-create-save-button`} className="mt-3 w-full" pendingText="Adding category…">Add category</SubmitButton></form>:null}</Card>; }

function TreatmentCard({service,salon=false}:{service:ServiceRow;salon?:boolean}) { return <Link id={`${salon?"salon-treatment":"service"}-card-${service.id}`} href={`/dashboard/services/${service.id}`} className="rounded-ui-lg border border-zinc-200 bg-white p-4 text-zinc-950 shadow-ui-sm hover:border-brand-border sm:p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><h2 className="font-semibold">{service.name}</h2>{service.is_add_on&&<span className="rounded-full bg-sky-100 px-2 py-1 text-xs font-bold text-sky-800">Add-on</span>}{!service.is_active&&<span className="rounded-full bg-zinc-200 px-2 py-1 text-xs font-bold">Inactive</span>}</div><p className="mt-1 text-sm text-zinc-600">{categoryName(service)}{service.short_description?` · ${service.short_description}`:""}</p>{salon&&<p className="mt-1 text-xs text-zinc-500">{availabilityLabel(service)}</p>}</div><div className="text-right"><p className="font-semibold">{formatMoney(service.base_price_centavos)}</p><p className="text-xs text-zinc-500">{formatDuration(service.duration_minutes)}</p>{salon&&<span className="mt-2 block text-xs font-bold text-brand-primary-strong">View</span>}</div></div></Link>; }
function EmptyServices({label}:{label:string}) { return <Card id={label==="treatment"?"salon-treatments-empty-state":"services-empty-state"} elevation="none" className="p-10 text-center"><h2 className="font-semibold">No {label}s found</h2><p className="mt-2 text-sm text-zinc-600">Add a {label} or clear the current filters.</p></Card>; }
