import Link from "next/link";
import { saveCategory,toggleCategory } from "@/app/dashboard/operations-actions";
import { FormMessage } from "@/components/form-message";
import { SubmitButton } from "@/components/submit-button";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { getDashboardContext } from "@/lib/auth/context";
import { formatDuration,formatMoney } from "@/lib/operations";
import { createClient } from "@/lib/supabase/server";

export default async function Page({searchParams}:{searchParams:Promise<{q?:string;category?:string;message?:string;error?:string}>}) {
  const [params,{activeMembership},supabase]=await Promise.all([searchParams,getDashboardContext(),createClient()]),search=params.q?.trim().replace(/[,%()]/g," ").slice(0,100);
  let query=supabase.from("services").select("id,name,short_description,duration_minutes,base_price_centavos,is_active,is_add_on,service_categories(name)").eq("organization_id",activeMembership.organizationId).order("name");
  if(search) query=query.ilike("name",`%${search}%`); if(params.category) query=query.eq("category_id",params.category);
  const [{data:services,error},{data:categories}]=await Promise.all([query,supabase.from("service_categories").select("id,name,sort_order,is_active").eq("organization_id",activeMembership.organizationId).order("sort_order").order("name")]),canManage=["owner","manager"].includes(activeMembership.role);
  return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-amber-700">Catalog and pricing</p><h1 className="mt-1 text-3xl font-black">Services</h1><p className="mt-2 text-zinc-600">Define what your shop offers, estimated duration, and trusted prices.</p></div>{canManage&&<Button asChild><Link href="/dashboard/services/new">Add service</Link></Button>}</div><FormMessage message={params.message} error={params.error??(error?"Unable to load services.":undefined)}/>
    <form className="mt-6 grid gap-2 sm:grid-cols-[1fr_220px_auto]"><Input name="q" defaultValue={params.q} placeholder="Search service name"/><select className="min-h-11 rounded-xl border border-zinc-200 bg-white px-3" name="category" defaultValue={params.category??""}><option value="">All categories</option>{categories?.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select><Button type="submit" variant="secondary">Search</Button></form>
    <div className="mt-6 grid gap-6 lg:grid-cols-[320px_1fr]"><Card className="h-fit p-5"><h2 className="font-black">Categories</h2><p className="mt-1 text-xs text-zinc-500">Edit names and sort order directly.</p><div className="mt-3 space-y-3">{categories?.map(category=><div key={category.id} className="rounded-xl border border-zinc-200 p-3">{canManage?<><form action={saveCategory} className="grid grid-cols-[1fr_70px_auto] gap-2"><input type="hidden" name="id" value={category.id}/><Input aria-label="Category name" required name="name" maxLength={100} defaultValue={category.name}/><Input aria-label="Sort order" required type="number" min={0} max={9999} name="sortOrder" defaultValue={category.sort_order}/><SubmitButton pendingText="…" variant="secondary">Save</SubmitButton></form><form action={toggleCategory} className="mt-2"><input type="hidden" name="id" value={category.id}/><input type="hidden" name="active" value={String(!category.is_active)}/><SubmitButton pendingText="…" variant="secondary">{category.is_active?"Deactivate":"Activate"}</SubmitButton></form></>:<span className={!category.is_active?"text-zinc-400":"font-semibold"}>{category.name}</span>}</div>)}</div>{canManage&&<form action={saveCategory} className="mt-5 border-t border-zinc-200 pt-4"><label className="text-sm font-semibold">New category<Input required name="name" maxLength={100}/></label><input type="hidden" name="sortOrder" value={categories?.length??0}/><SubmitButton className="mt-3 w-full" pendingText="Adding…">Add category</SubmitButton></form>}</Card>
      <div className="grid gap-3">{services?.map(service=>{const category=Array.isArray(service.service_categories)?service.service_categories[0]:service.service_categories;return <Link key={service.id} href={`/dashboard/services/${service.id}`} className="rounded-2xl border border-zinc-200 bg-white p-5 text-zinc-950 shadow-sm hover:border-amber-300"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><h2 className="font-black">{service.name}</h2>{service.is_add_on&&<span className="rounded-full bg-sky-100 px-2 py-1 text-xs font-bold text-sky-800">Add-on</span>}{!service.is_active&&<span className="rounded-full bg-zinc-200 px-2 py-1 text-xs font-bold">Inactive</span>}</div><p className="mt-1 text-sm text-zinc-600">{category?.name??"Uncategorized"}{service.short_description?` · ${service.short_description}`:""}</p></div><div className="text-right"><p className="font-black">{formatMoney(service.base_price_centavos)}</p><p className="text-xs text-zinc-500">{formatDuration(service.duration_minutes)}</p></div></div></Link>})}{services?.length===0&&<Card className="p-10 text-center"><h2 className="font-black">No services found</h2><p className="mt-2 text-sm text-zinc-600">Add a service or clear the current filters.</p></Card>}</div>
    </div>
  </div>;
}
