"use server";
import{redirect}from"next/navigation";
import{formValue}from"@/lib/crm";
import{reportActionError}from"@/lib/errors/action-error";
import{zonedDateTimeToUtc}from"@/lib/operations";
import{appointmentSelfServiceTokenSchema}from"@/modules/core/scheduling/appointment-self-service";
import{getPublicAppointmentSelfService,updatePublicAppointmentSelfService}from"@/modules/core/scheduling/appointment-self-service.runtime";
function go(token:string,kind:"message"|"error",message:string):never{redirect(`/appointment/${token}?${kind}=${encodeURIComponent(message)}`)}
export async function updatePublicSalonAppointment(data:FormData){const rawToken=formValue(data,"token"),token=appointmentSelfServiceTokenSchema.safeParse(rawToken);if(!token.success)redirect("/appointment/invalid");const action=formValue(data,"action");if(action!=="confirm"&&action!=="reschedule")go(token.data,"error","Invalid appointment action.");let startsAt:string|undefined;if(action==="reschedule"){let current;try{current=await getPublicAppointmentSelfService(token.data);}catch(error){go(token.data,"error",reportActionError("public_appointment.load",error,"Unable to load your appointment. Please try again."));}if(current.state!=="active")go(token.data,"error","This appointment link is no longer available.");const parsed=zonedDateTimeToUtc(formValue(data,"startsAt"),current.branchTimezone);if(!parsed)go(token.data,"error","Choose a valid appointment date and time.");startsAt=parsed.toISOString();}let result;try{result=await updatePublicAppointmentSelfService(token.data,action,startsAt);}catch(error){go(token.data,"error",reportActionError("public_appointment.update",error,"Unable to update your appointment. Please try again."));}if(!["confirmed","rescheduled"].includes(result.state))go(token.data,"error","This appointment link is no longer available.");go(token.data,"message",action==="confirm"?"Your appointment is confirmed.":"Your appointment has been rescheduled.");}
