import Link from "next/link";
import { Search } from "lucide-react";
import { FormMessage } from "@/components/form-message";
import { EmptyState, FilterBar, PageHeader } from "@/components/page-patterns";
import { Button } from "@/components/ui/button";
import { getDashboardContext } from "@/lib/auth/context";
import { jobNumber } from "@/lib/jobs";
import { formatMoney } from "@/lib/operations";
import { createClient } from "@/lib/supabase/server";

export default async function JobsPage({searchParams}:{searchParams:Promise<{q?:string;status?:string;message?:string;error?:string}>}) {
  const[p,{activeMembership},supabase]=await Promise.all([searchParams,getDashboardContext(),createClient()]);
  let query=supabase.from("job_orders").select("id,job_number,status,created_at,actual_total_centavos,primary_technician_staff_id,customers(full_name),vehicles(make,model,plate_number),job_order_items(service_name_snapshot)").eq("organization_id",activeMembership.organizationId).eq("branch_id",activeMembership.branchId).order("created_at",{ascending:false}).limit(100);
  if(p.status)query=query.eq("status",p.status);
  const{data,error}=await query,q=p.q?.trim().toLowerCase(),rows=(data??[]).filter(row=>!q||JSON.stringify(row).toLowerCase().includes(q));
  return <main id="job-orders-page" className="mx-auto max-w-7xl">
    <PageHeader id="job-orders-page-header" eyebrow={activeMembership.branchName} title="Job Orders" description="Live service-bay work, inspections, approvals, and release."/>
    <FormMessage {...p} error={p.error??(error?"Unable to load jobs.":undefined)}/>
    <FilterBar id="job-orders-filter-bar"><form id="job-orders-filter-form" className="grid gap-2 sm:grid-cols-[minmax(16rem,1fr)_13rem_auto]"><label className="relative"><span className="sr-only">Search job orders</span><Search className="absolute left-3 top-3.5 text-zinc-400" size={18}/><input id="job-orders-search-input" className="min-h-11 w-full rounded-xl border border-zinc-200 bg-white pl-10 pr-3" name="q" defaultValue={p.q} placeholder="Job number, customer, plate, or service"/></label><select id="job-orders-status-filter" className="min-h-11 rounded-xl border border-zinc-200 bg-white px-3 capitalize" name="status" defaultValue={p.status??""}><option value="">All statuses</option>{["queued","in_progress","on_hold","quality_check","ready_for_release","completed","cancelled"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select><Button type="submit" variant="secondary">Filter</Button></form></FilterBar>
    {rows.length?<><div className="mt-4 hidden overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm md:block"><table id="job-orders-table" className="w-full text-left text-sm"><thead className="bg-zinc-50 text-xs uppercase tracking-wide text-zinc-500"><tr><th className="px-4 py-3">Job</th><th className="px-4 py-3">Vehicle / customer</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Technician</th><th className="px-4 py-3 text-right">Amount</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-zinc-100">{rows.map(row=>{const c=Array.isArray(row.customers)?row.customers[0]:row.customers,v=Array.isArray(row.vehicles)?row.vehicles[0]:row.vehicles;return <tr id={`job-order-row-${row.id}`} key={row.id} className="hover:bg-blue-50/80"><td className="px-4 py-3 font-black">{jobNumber(row.job_number??0,new Date(row.created_at).getFullYear())}<span className="block text-xs font-normal text-zinc-500">{new Intl.DateTimeFormat("en-PH",{dateStyle:"medium"}).format(new Date(row.created_at))}</span></td><td className="px-4 py-3"><strong>{v?.make} {v?.model}{v?.plate_number?` · ${v.plate_number}`:""}</strong><span className="block text-xs text-zinc-500">{c?.full_name}</span></td><td className="px-4 py-3 font-semibold capitalize">{row.status.replaceAll("_"," ")}</td><td className="px-4 py-3 text-zinc-600">{row.primary_technician_staff_id?"Assigned":"Unassigned"}</td><td className="px-4 py-3 text-right"><strong>{formatMoney(row.actual_total_centavos)}</strong></td><td className="px-4 py-3 text-right"><Button asChild size="sm" variant="secondary"><Link href={`/dashboard/jobs/${row.id}`}>Open</Link></Button></td></tr>})}</tbody></table></div>
      <div id="job-orders-mobile-list" className="mt-4 grid gap-2 md:hidden">{rows.map(row=>{const c=Array.isArray(row.customers)?row.customers[0]:row.customers,v=Array.isArray(row.vehicles)?row.vehicles[0]:row.vehicles;return <Link id={`job-order-card-${row.id}`} href={`/dashboard/jobs/${row.id}`} key={row.id} className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><strong>{jobNumber(row.job_number??0,new Date(row.created_at).getFullYear())}</strong><span className="text-xs font-bold capitalize">{row.status.replaceAll("_"," ")}</span></div><h2 className="mt-2 font-black">{v?.make} {v?.model}{v?.plate_number?` · ${v.plate_number}`:""}</h2><p className="text-sm text-zinc-600">{c?.full_name}</p><div className="mt-3 flex justify-between border-t border-zinc-100 pt-3 text-xs text-zinc-500"><span>{row.primary_technician_staff_id?"Technician assigned":"Unassigned"}</span><strong>{formatMoney(row.actual_total_centavos)}</strong></div></Link>})}</div></>:<div className="mt-4"><EmptyState id="job-orders-empty-state" title={q||p.status?"No results match your filters":"No job orders yet"} description={q||p.status?"Try a different search or clear the current filters.":"Job orders appear here after a queue entry is converted."} action={q||p.status?<Button asChild variant="secondary"><Link href="/dashboard/jobs">Clear filters</Link></Button>:undefined}/></div>}
  </main>;
}
