-- Phase 05-06 completion: typed transitions, proposed work, and financial reversals.

create or replace function public.transition_job(p_job_id uuid,p_action text) returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare j public.job_orders; target public.job_status;
begin select * into j from public.job_orders where id=p_job_id for update;
  if j.id is null or not public.has_org_role(j.organization_id,array['owner','manager','advisor','technician']::public.organization_role[]) then raise exception 'Job not found' using errcode='42501'; end if;
  if public.has_org_role(j.organization_id,array['technician']::public.organization_role[]) and j.primary_technician_user_id is distinct from auth.uid() then raise exception 'Job not assigned' using errcode='42501'; end if;
  target:=case when p_action='start' and j.status in ('queued','approved') then 'in_progress'::public.job_status when p_action='hold' and j.status='in_progress' then 'on_hold'::public.job_status when p_action='resume' and j.status='on_hold' then 'in_progress'::public.job_status when p_action='quality_check' and j.status='in_progress' then 'quality_check'::public.job_status when p_action='ready' and j.status='quality_check' then 'ready_for_release'::public.job_status when p_action='complete' and j.status in ('ready','ready_for_release') then 'completed'::public.job_status when p_action='cancel' and j.status in ('draft','queued') then 'cancelled'::public.job_status else null::public.job_status end;
  if target is null then raise exception 'Invalid job transition'; end if;
  update public.job_orders set status=target,started_at=case when target='in_progress' and started_at is null then now() else started_at end,completed_at=case when target='completed' then now() else completed_at end where id=j.id;
end $$;

create or replace function public.transition_estimate(p_estimate_id uuid,p_action text,p_note text default null) returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare e public.estimates; target public.estimate_status;
begin select * into e from public.estimates where id=p_estimate_id for update; if e.id is null or not public.has_org_role(e.organization_id,array['owner','manager','advisor']::public.organization_role[]) then raise exception 'Estimate not found' using errcode='42501'; end if;
target:=case when p_action='send' and e.status='draft' then 'sent'::public.estimate_status when p_action='approve' and e.status in ('draft','sent') then 'approved'::public.estimate_status when p_action='decline' and e.status in ('draft','sent') then 'declined'::public.estimate_status else null::public.estimate_status end; if target is null then raise exception 'Invalid estimate transition'; end if;
update public.estimates set status=target,approved_at=case when target='approved' then now() else approved_at end,approved_by=case when target='approved' then auth.uid() else approved_by end,approval_note=nullif(trim(coalesce(p_note,'')),'') where id=e.id; update public.job_orders set status=case when target='approved' then 'approved'::public.job_status else status end where id=e.job_order_id; end $$;

create or replace function public.record_invoice_payment(p_invoice_id uuid,p_amount_centavos bigint,p_method public.payment_method,p_reference text default null,p_notes text default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare i public.invoices; pid uuid; new_paid bigint;
begin select * into i from public.invoices where id=p_invoice_id for update; if i.id is null or not public.has_org_role(i.organization_id,array['owner','manager','cashier']::public.organization_role[]) then raise exception 'Invoice not found' using errcode='42501'; end if;if i.status not in ('issued','partially_paid') or p_amount_centavos<=0 or p_amount_centavos>i.balance_centavos then raise exception 'Invalid payment amount';end if;
insert into public.payments(organization_id,branch_id,job_order_id,invoice_id,amount_centavos,method,status,reference,paid_at,notes,received_by,created_by) values(i.organization_id,i.branch_id,i.job_order_id,i.id,p_amount_centavos,p_method,'paid',nullif(trim(coalesce(p_reference,'')),''),now(),nullif(trim(coalesce(p_notes,'')),''),auth.uid(),auth.uid()) returning id into pid;new_paid:=i.paid_centavos+p_amount_centavos;update public.invoices set paid_centavos=new_paid,balance_centavos=total_centavos-new_paid,status=case when new_paid=total_centavos then 'paid'::public.invoice_status else 'partially_paid'::public.invoice_status end where id=i.id;return pid;end $$;

create function public.add_job_service(p_job_id uuid,p_service_id uuid,p_quantity integer default 1,p_requires_approval boolean default true,p_notes text default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare j public.job_orders; s public.services; vehicle_class text; price bigint; item_id uuid;
begin select * into j from public.job_orders where id=p_job_id for update; if j.id is null or not public.has_org_role(j.organization_id,array['owner','manager','advisor']::public.organization_role[]) then raise exception 'Job not found' using errcode='42501'; end if; if j.status in ('completed','cancelled') or p_quantity<1 or p_quantity>100 then raise exception 'Job cannot accept work'; end if;
select * into s from public.services where id=p_service_id and organization_id=j.organization_id and is_active; if s.id is null then raise exception 'Service unavailable'; end if; select lower(replace(coalesce(vehicle_type,'custom'),' ','_')) into vehicle_class from public.vehicles where id=j.vehicle_id; price:=public.resolve_service_price(s.id,j.branch_id,vehicle_class); if price is null then raise exception 'Price unavailable'; end if;
insert into public.job_order_items(organization_id,job_order_id,service_id,service_name_snapshot,quantity,unit_price_centavos,discount_centavos,line_total_centavos,duration_minutes,approval_status,notes) values(j.organization_id,j.id,s.id,s.name,p_quantity,price,0,price*p_quantity,s.duration_minutes,case when p_requires_approval then 'proposed' else 'approved' end,p_notes) returning id into item_id;
if p_requires_approval then update public.job_orders set status='awaiting_approval' where id=j.id and status not in ('draft','awaiting_approval'); end if; return item_id; end $$;

create function public.transition_job_service(p_item_id uuid,p_action text) returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare item public.job_order_items; job public.job_orders; target text;
begin select * into item from public.job_order_items where id=p_item_id for update; select * into job from public.job_orders where id=item.job_order_id for update; if item.id is null or not public.has_org_role(item.organization_id,array['owner','manager','advisor']::public.organization_role[]) then raise exception 'Job item not found' using errcode='42501'; end if; if item.approval_status<>'proposed' or p_action not in ('approve','decline') then raise exception 'Invalid item transition'; end if; target:=case when p_action='approve' then 'approved' else 'declined' end; update public.job_order_items set approval_status=target where id=item.id; if not exists(select 1 from public.job_order_items where job_order_id=job.id and approval_status='proposed' and id<>item.id) then update public.job_orders set status=case when target='approved' then 'approved'::public.job_status else 'in_progress'::public.job_status end where id=job.id; end if; end $$;

create function public.reverse_payment(p_payment_id uuid,p_action text,p_note text) returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare payment public.payments; invoice public.invoices; next_paid bigint;
begin select * into payment from public.payments where id=p_payment_id for update; if payment.id is null or not public.has_org_role(payment.organization_id,array['owner','manager','cashier']::public.organization_role[]) then raise exception 'Payment not found' using errcode='42501'; end if; if payment.status<>'paid' or p_action not in ('refund','void') then raise exception 'Payment cannot be reversed'; end if; select * into invoice from public.invoices where id=payment.invoice_id for update; next_paid:=invoice.paid_centavos-payment.amount_centavos; if next_paid<0 then raise exception 'Invalid invoice balance'; end if; update public.payments set status=case when p_action='refund' then 'refunded'::public.payment_status else 'voided'::public.payment_status end,notes=concat_ws(E'\n',notes,nullif(trim(coalesce(p_note,'')),'')) where id=payment.id; update public.invoices set paid_centavos=next_paid,balance_centavos=total_centavos-next_paid,status=case when next_paid=0 then 'issued'::public.invoice_status else 'partially_paid'::public.invoice_status end where id=invoice.id; end $$;

create function public.void_invoice(p_invoice_id uuid,p_reason text) returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare invoice public.invoices;
begin select * into invoice from public.invoices where id=p_invoice_id for update; if invoice.id is null or not public.has_org_role(invoice.organization_id,array['owner','manager']::public.organization_role[]) then raise exception 'Invoice not found' using errcode='42501'; end if; if invoice.paid_centavos<>0 or invoice.status not in ('issued','draft') then raise exception 'Paid invoice cannot be voided'; end if; update public.invoices set status='void',voided_at=now(),notes=concat_ws(E'\n',notes,'Void reason: '||nullif(trim(coalesce(p_reason,'')),'')) where id=invoice.id; end $$;

grant execute on function public.add_job_service(uuid,uuid,integer,boolean,text),public.transition_job_service(uuid,text),public.reverse_payment(uuid,text,text),public.void_invoice(uuid,text) to authenticated;
