-- Phase 10: curated public storefront and isolated online booking requests.
alter table public.organizations add column public_page_enabled boolean not null default false,add column public_description text,add column logo_url text,add column cover_url text,add column instagram_url text;
alter table public.branches add column public_description text,add column map_url text,add column opening_hours jsonb not null default '{"monday":{"open":"08:00","close":"17:00"},"tuesday":{"open":"08:00","close":"17:00"},"wednesday":{"open":"08:00","close":"17:00"},"thursday":{"open":"08:00","close":"17:00"},"friday":{"open":"08:00","close":"17:00"},"saturday":{"open":"08:00","close":"17:00"},"sunday":{"closed":true}}'::jsonb,add column accepts_public_bookings boolean not null default true;
alter table public.services add column is_public boolean not null default false;

create table public.shop_gallery_images(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,url text not null,alt_text text not null,sort_order integer not null default 0,is_active boolean not null default true,created_at timestamptz not null default now());
create type public.public_booking_status as enum('requested','confirmed','declined','cancelled');
create table public.public_booking_requests(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid not null references public.branches(id) on delete restrict,
 status public.public_booking_status not null default 'requested',public_reference text not null unique,confirmation_token_hash text not null unique,
 customer_name text not null,phone text not null,phone_normalized text not null,email text,email_normalized text,
 vehicle_make text not null,vehicle_model text not null,vehicle_year integer,vehicle_type text,plate_number text,plate_normalized text,
 preferred_at timestamptz not null,customer_note text,duplicate_hash text not null,rate_key_hash text not null,
 appointment_id uuid references public.appointments(id) on delete set null,reviewed_by uuid references auth.users(id),reviewed_at timestamptz,decline_reason text,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(vehicle_year is null or vehicle_year between 1900 and 2200)
);
create unique index public_booking_pending_duplicate on public.public_booking_requests(organization_id,duplicate_hash) where status='requested';
create table public.public_booking_services(booking_request_id uuid not null references public.public_booking_requests(id) on delete cascade,service_id uuid not null references public.services(id) on delete restrict,service_name_snapshot text not null,price_centavos bigint not null,duration_minutes integer not null,primary key(booking_request_id,service_id));
create table public.public_booking_rate_limits(key_hash text not null,window_started_at timestamptz not null,request_count integer not null default 0,primary key(key_hash,window_started_at));

create function public.get_public_shop(p_slug text) returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
 select jsonb_build_object('slug',o.slug,'name',o.name,'description',o.public_description,'logoUrl',o.logo_url,'coverUrl',o.cover_url,'phone',o.phone,'email',o.email,'website',o.website,'facebook',o.facebook_page,'instagram',o.instagram_url,
 'branches',coalesce((select jsonb_agg(jsonb_build_object('id',b.id,'name',b.name,'description',b.public_description,'phone',b.phone,'email',b.email,'address',array[b.address_line,b.barangay,b.city,b.province,b.postal_code,b.country],'mapUrl',b.map_url,'hours',b.opening_hours,'acceptsBookings',b.accepts_public_bookings) order by b.is_primary desc,b.name) from public.branches b where b.organization_id=o.id and b.is_active),'[]'::jsonb),
 'services',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'name',s.name,'description',s.description,'durationMinutes',s.duration_minutes,'priceCentavos',s.base_price_centavos,'category',c.name) order by c.sort_order,s.name) from public.services s left join public.service_categories c on c.id=s.category_id where s.organization_id=o.id and s.is_active and s.is_public),'[]'::jsonb),
 'gallery',coalesce((select jsonb_agg(jsonb_build_object('url',g.url,'alt',g.alt_text) order by g.sort_order,g.created_at) from public.shop_gallery_images g where g.organization_id=o.id and g.is_active),'[]'::jsonb))
 from public.organizations o where o.slug=lower(trim(p_slug)) and o.status='active' and o.public_page_enabled
$$;
create function public.list_public_shops() returns table(slug text,updated_at timestamptz) language sql stable security definer set search_path=public,pg_temp as $$select slug,updated_at from public.organizations where public_page_enabled and status='active'$$;

create function public.get_public_availability(p_slug text,p_branch_id uuid,p_service_id uuid,p_date date) returns table(slot_at timestamptz) language plpgsql stable security definer set search_path=public,pg_temp as $$
declare org_id uuid; hours jsonb; tz text; open_time time; close_time time; day_key text; duration integer;
begin if p_date<current_date or p_date>current_date+60 then return; end if; select o.id into org_id from public.organizations o where o.slug=lower(trim(p_slug)) and o.public_page_enabled and o.status='active';
 select b.opening_hours,b.timezone into hours,tz from public.branches b where b.id=p_branch_id and b.organization_id=org_id and b.is_active and b.accepts_public_bookings;
 if hours is null or not exists(select 1 from public.services s where s.id=p_service_id and s.organization_id=org_id and s.is_active and s.is_public and (not exists(select 1 from public.service_branch_availability a where a.service_id=s.id) or exists(select 1 from public.service_branch_availability a where a.service_id=s.id and a.branch_id=p_branch_id and a.is_available))) then return; end if;
 day_key:=lower(to_char(p_date,'FMDay')); if coalesce((hours->day_key->>'closed')::boolean,false) then return; end if; open_time:=coalesce((hours->day_key->>'open')::time,'08:00');close_time:=coalesce((hours->day_key->>'close')::time,'17:00');select duration_minutes into duration from public.services where id=p_service_id;
 return query select candidate from generate_series((p_date+open_time) at time zone tz,((p_date+close_time) at time zone tz)-make_interval(mins=>duration),interval '30 minutes') candidate where candidate>now()+interval '1 hour' and not exists(select 1 from public.appointments a where a.branch_id=p_branch_id and a.status not in('cancelled','no_show') and tstzrange(a.starts_at,coalesce(a.ends_at,a.starts_at+interval '1 hour'),'[)')&&tstzrange(candidate,candidate+make_interval(mins=>duration),'[)'));
end $$;

create function public.submit_public_booking(p_slug text,p_branch_id uuid,p_service_ids uuid[],p_preferred_at timestamptz,p_customer_name text,p_phone text,p_email text,p_vehicle_make text,p_vehicle_model text,p_vehicle_year integer,p_vehicle_type text,p_plate_number text,p_customer_note text,p_rate_key_hash text,p_honeypot text default '') returns jsonb language plpgsql security definer set search_path=public,extensions,pg_temp as $$
declare org_id uuid; request_id uuid; token text:=encode(gen_random_bytes(32),'hex'); reference text; normalized_phone text;normalized_email text;normalized_plate text;dup text;window_time timestamptz:=date_trunc('hour',now())+(floor(extract(minute from now())/15)*interval '15 minutes');current_count integer;service_id uuid;
begin if coalesce(p_honeypot,'')<>'' then raise exception 'Unable to submit booking'; end if;if coalesce(array_length(p_service_ids,1),0)<1 or array_length(p_service_ids,1)>10 or p_preferred_at<now()+interval '1 hour' or p_preferred_at>now()+interval '60 days' then raise exception 'Invalid booking request';end if;
 if char_length(trim(p_customer_name)) not between 2 and 120 or char_length(trim(p_phone)) not between 7 and 30 or char_length(trim(p_vehicle_make)) not between 1 and 80 or char_length(trim(p_vehicle_model)) not between 1 and 80 or char_length(coalesce(p_customer_note,''))>1000 then raise exception 'Invalid booking details';end if;
 select o.id into org_id from public.organizations o where o.slug=lower(trim(p_slug)) and o.public_page_enabled and o.status='active';if org_id is null or not exists(select 1 from public.branches b where b.id=p_branch_id and b.organization_id=org_id and b.is_active and b.accepts_public_bookings) then raise exception 'Shop unavailable';end if;
 if exists(select 1 from unnest(p_service_ids) sid where not exists(select 1 from public.services s where s.id=sid and s.organization_id=org_id and s.is_active and s.is_public)) then raise exception 'Service unavailable';end if;
 insert into public.public_booking_rate_limits(key_hash,window_started_at,request_count) values(p_rate_key_hash,window_time,1) on conflict(key_hash,window_started_at) do update set request_count=public.public_booking_rate_limits.request_count+1 returning request_count into current_count;if current_count>5 then raise exception 'Too many booking requests';end if;
 normalized_phone:=regexp_replace(p_phone,'[^0-9+]','','g');normalized_email:=nullif(lower(trim(coalesce(p_email,''))),'');normalized_plate:=nullif(upper(regexp_replace(coalesce(p_plate_number,''),'[^A-Za-z0-9]','','g')),'');dup:=encode(digest(org_id::text||p_branch_id::text||normalized_phone||coalesce(normalized_email,'')||p_preferred_at::text||array_to_string(p_service_ids,','),'sha256'),'hex');reference:='BK-'||upper(substr(encode(gen_random_bytes(8),'hex'),1,10));
 insert into public.public_booking_requests(organization_id,branch_id,public_reference,confirmation_token_hash,customer_name,phone,phone_normalized,email,email_normalized,vehicle_make,vehicle_model,vehicle_year,vehicle_type,plate_number,plate_normalized,preferred_at,customer_note,duplicate_hash,rate_key_hash) values(org_id,p_branch_id,reference,encode(digest(token,'sha256'),'hex'),trim(p_customer_name),trim(p_phone),normalized_phone,normalized_email,normalized_email,trim(p_vehicle_make),trim(p_vehicle_model),p_vehicle_year,nullif(trim(coalesce(p_vehicle_type,'')),''),nullif(trim(coalesce(p_plate_number,'')),''),normalized_plate,p_preferred_at,nullif(trim(coalesce(p_customer_note,'')),''),dup,p_rate_key_hash) returning id into request_id;
 foreach service_id in array p_service_ids loop insert into public.public_booking_services(booking_request_id,service_id,service_name_snapshot,price_centavos,duration_minutes) select request_id,s.id,s.name,public.resolve_service_price(s.id,p_branch_id,lower(replace(coalesce(p_vehicle_type,'custom'),' ','_'))),s.duration_minutes from public.services s where s.id=service_id;end loop;
 return jsonb_build_object('reference',reference,'token',token);exception when unique_violation then raise exception 'A similar booking request is already pending';end $$;

create function public.get_public_booking_status(p_token text) returns jsonb language sql stable security definer set search_path=public,extensions,pg_temp as $$
 select jsonb_build_object('reference',r.public_reference,'status',r.status,'shopName',o.name,'branchName',b.name,'preferredAt',r.preferred_at,'services',(select jsonb_agg(s.service_name_snapshot) from public.public_booking_services s where s.booking_request_id=r.id),'declineReason',case when r.status='declined' then r.decline_reason end) from public.public_booking_requests r join public.organizations o on o.id=r.organization_id join public.branches b on b.id=r.branch_id where r.confirmation_token_hash=encode(digest(p_token,'sha256'),'hex')
$$;

create function public.review_public_booking(p_booking_id uuid,p_action text,p_reason text default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare r public.public_booking_requests;customer_id uuid;vehicle_id uuid;new_appointment_id uuid;item record;
begin select * into r from public.public_booking_requests where id=p_booking_id for update;if r.id is null or not public.has_permission(r.organization_id,'appointments.manage') or not public.can_access_branch(r.organization_id,r.branch_id) then raise exception 'Booking request not found' using errcode='42501';end if;if r.status<>'requested' or p_action not in('confirm','decline') then raise exception 'Invalid booking transition';end if;
 if p_action='decline' then update public.public_booking_requests set status='declined',decline_reason=nullif(trim(coalesce(p_reason,'')),''),reviewed_by=auth.uid(),reviewed_at=now() where id=r.id;return null;end if;
 select id into customer_id from public.customers where organization_id=r.organization_id and (phone_normalized=r.phone_normalized or (r.email_normalized is not null and lower(email)=r.email_normalized)) order by created_at limit 1;
 if customer_id is null then insert into public.customers(organization_id,full_name,phone,phone_normalized,email,created_by) values(r.organization_id,r.customer_name,r.phone,r.phone_normalized,r.email_normalized,auth.uid()) returning id into customer_id;end if;
 if r.plate_normalized is not null then select id into vehicle_id from public.vehicles where organization_id=r.organization_id and customer_id=customer_id and plate_normalized=r.plate_normalized limit 1;end if;
 if vehicle_id is null then insert into public.vehicles(organization_id,customer_id,make,model,model_year,vehicle_type,plate_number,plate_normalized) values(r.organization_id,customer_id,r.vehicle_make,r.vehicle_model,r.vehicle_year,r.vehicle_type,r.plate_number,r.plate_normalized) returning id into vehicle_id;end if;
 insert into public.appointments(organization_id,branch_id,customer_id,vehicle_id,status,source,starts_at,customer_note,created_by) values(r.organization_id,r.branch_id,customer_id,vehicle_id,'confirmed','public_booking',r.preferred_at,r.customer_note,auth.uid()) returning id into new_appointment_id;
 for item in select service_id from public.public_booking_services where booking_request_id=r.id loop insert into public.appointment_services(appointment_id,service_id,service_name_snapshot,unit_price_centavos,duration_minutes) values(new_appointment_id,item.service_id,'pending',0,1);end loop;
 update public.public_booking_requests set status='confirmed',appointment_id=new_appointment_id,reviewed_by=auth.uid(),reviewed_at=now() where id=r.id;return new_appointment_id;end $$;

alter table public.shop_gallery_images enable row level security;alter table public.public_booking_requests enable row level security;alter table public.public_booking_services enable row level security;alter table public.public_booking_rate_limits enable row level security;
create policy gallery_member_select on public.shop_gallery_images for select to authenticated using(public.is_org_member(organization_id));create policy gallery_manage on public.shop_gallery_images for all to authenticated using(public.has_permission(organization_id,'settings.manage')) with check(public.has_permission(organization_id,'settings.manage'));
create policy booking_member_select on public.public_booking_requests for select to authenticated using(public.is_org_member(organization_id) and public.can_access_branch(organization_id,branch_id));create policy booking_services_member_select on public.public_booking_services for select to authenticated using(exists(select 1 from public.public_booking_requests r where r.id=booking_request_id and public.is_org_member(r.organization_id) and public.can_access_branch(r.organization_id,r.branch_id)));
grant select,insert,update,delete on public.shop_gallery_images to authenticated;grant select on public.public_booking_requests,public.public_booking_services to authenticated;
grant execute on function public.get_public_shop(text),public.list_public_shops(),public.get_public_availability(text,uuid,uuid,date),public.submit_public_booking(text,uuid,uuid[],timestamptz,text,text,text,text,text,integer,text,text,text,text,text),public.get_public_booking_status(text) to anon,authenticated;grant execute on function public.review_public_booking(uuid,text,text) to authenticated;
create trigger booking_updated_at before update on public.public_booking_requests for each row execute function public.set_updated_at();
create trigger booking_actor_branch before update or delete on public.public_booking_requests for each row execute function public.enforce_actor_branch_access();
