-- Resolve PL/pgSQL identifiers explicitly in public booking review.
create or replace function public.review_public_booking(p_booking_id uuid,p_action text,p_reason text default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare r public.public_booking_requests;cust_id uuid;veh_id uuid;new_appointment_id uuid;item record;
begin select * into r from public.public_booking_requests where id=p_booking_id for update;if r.id is null or not public.has_permission(r.organization_id,'appointments.manage') or not public.can_access_branch(r.organization_id,r.branch_id) then raise exception 'Booking request not found' using errcode='42501';end if;if r.status<>'requested' or p_action not in('confirm','decline') then raise exception 'Invalid booking transition';end if;
 if p_action='decline' then update public.public_booking_requests set status='declined',decline_reason=nullif(trim(coalesce(p_reason,'')),''),reviewed_by=auth.uid(),reviewed_at=now() where id=r.id;return null;end if;
 select c.id into cust_id from public.customers c where c.organization_id=r.organization_id and (c.phone_normalized=r.phone_normalized or (r.email_normalized is not null and lower(c.email)=r.email_normalized)) order by c.created_at limit 1;
 if cust_id is null then insert into public.customers(organization_id,full_name,phone,phone_normalized,email,created_by) values(r.organization_id,r.customer_name,r.phone,r.phone_normalized,r.email_normalized,auth.uid()) returning id into cust_id;end if;
 if r.plate_normalized is not null then select v.id into veh_id from public.vehicles v where v.organization_id=r.organization_id and v.customer_id=cust_id and v.plate_normalized=r.plate_normalized limit 1;end if;
 if veh_id is null then insert into public.vehicles(organization_id,customer_id,make,model,model_year,vehicle_type,plate_number,plate_normalized) values(r.organization_id,cust_id,r.vehicle_make,r.vehicle_model,r.vehicle_year,r.vehicle_type,r.plate_number,r.plate_normalized) returning id into veh_id;end if;
 insert into public.appointments(organization_id,branch_id,customer_id,vehicle_id,status,source,starts_at,customer_note,created_by) values(r.organization_id,r.branch_id,cust_id,veh_id,'confirmed','public_booking',r.preferred_at,r.customer_note,auth.uid()) returning id into new_appointment_id;
 for item in select service_id from public.public_booking_services where booking_request_id=r.id loop insert into public.appointment_services(appointment_id,service_id,service_name_snapshot,unit_price_centavos,duration_minutes) values(new_appointment_id,item.service_id,'pending',0,1);end loop;
 update public.public_booking_requests set status='confirmed',appointment_id=new_appointment_id,reviewed_by=auth.uid(),reviewed_at=now() where id=r.id;return new_appointment_id;end $$;
