-- Phase 11 reconciliation completion and Phase 12 subscriptions/entitlements.

alter table public.invoice_items add column job_order_item_id uuid references public.job_order_items(id) on delete restrict;
alter table public.invoice_items add column service_id uuid references public.services(id) on delete set null;
alter table public.invoice_items add column category_name_snapshot text;
alter table public.invoice_items add column recognized_revenue_centavos bigint not null default 0 check(recognized_revenue_centavos>=0);

create function public.allocate_invoice_revenue(p_invoice_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare target_total bigint; base_total bigint; remainder bigint;
begin
  select total_centavos into target_total from public.invoices where id=p_invoice_id;
  if target_total is null then raise exception 'Invoice not found'; end if;
  select coalesce(sum(line_total_centavos),0) into base_total from public.invoice_items where invoice_id=p_invoice_id;
  if base_total=0 then update public.invoice_items set recognized_revenue_centavos=0 where invoice_id=p_invoice_id; return; end if;
  update public.invoice_items set recognized_revenue_centavos=(target_total*line_total_centavos/base_total) where invoice_id=p_invoice_id;
  select target_total-coalesce(sum(recognized_revenue_centavos),0) into remainder from public.invoice_items where invoice_id=p_invoice_id;
  with ranked as(select id,row_number() over(order by ((target_total*line_total_centavos)%base_total) desc,id) n from public.invoice_items where invoice_id=p_invoice_id)
  update public.invoice_items i set recognized_revenue_centavos=i.recognized_revenue_centavos+1 from ranked r where i.id=r.id and r.n<=remainder;
end $$;
revoke all on function public.allocate_invoice_revenue(uuid) from public,anon,authenticated;

create or replace function public.issue_invoice(p_job_id uuid,p_estimate_id uuid default null,p_notes text default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare j public.job_orders;e public.estimates;inv uuid;next_no bigint;yr integer;number_text text;cname text;vname text;subtotal bigint;discount bigint:=0;tax bigint:=0;total bigint;
begin select * into j from public.job_orders where id=p_job_id for update;if j.id is null or not public.has_org_role(j.organization_id,array['owner','manager','cashier']::public.organization_role[]) then raise exception 'Job not found' using errcode='42501';end if;if exists(select 1 from public.invoices where job_order_id=j.id)then raise exception 'Job already invoiced';end if;
if p_estimate_id is not null then select * into e from public.estimates where id=p_estimate_id and job_order_id=j.id and status='approved';if e.id is null then raise exception 'Approved estimate required';end if;subtotal:=e.subtotal_centavos;discount:=e.discount_centavos;tax:=e.tax_centavos;total:=e.total_centavos;else select coalesce(sum(line_total_centavos),0)into subtotal from public.job_order_items where job_order_id=j.id and approval_status='approved';total:=subtotal;end if;
select full_name into cname from public.customers where id=j.customer_id;select concat_ws(' ',make,model,plate_number)into vname from public.vehicles where id=j.vehicle_id;yr:=extract(year from now()at time zone 'Asia/Manila');insert into public.invoice_number_counters(branch_id,number_year,last_number)values(j.branch_id,yr,1)on conflict(branch_id,number_year)do update set last_number=public.invoice_number_counters.last_number+1 returning last_number into next_no;number_text:='INV-'||yr||'-'||lpad(next_no::text,6,'0');
insert into public.invoices(organization_id,branch_id,job_order_id,estimate_id,invoice_number,status,customer_name_snapshot,vehicle_snapshot,subtotal_centavos,discount_centavos,tax_centavos,total_centavos,balance_centavos,issued_at,notes,created_by)values(j.organization_id,j.branch_id,j.id,p_estimate_id,number_text,'issued',cname,vname,subtotal,discount,tax,total,total,now(),p_notes,auth.uid())returning id into inv;
if p_estimate_id is not null then insert into public.invoice_items(invoice_id,organization_id,job_order_item_id,service_id,category_name_snapshot,description_snapshot,quantity,unit_price_centavos,discount_centavos,line_total_centavos)select inv,j.organization_id,ei.job_order_item_id,ji.service_id,coalesce(sc.name,'Uncategorized'),ei.description_snapshot,ei.quantity,ei.unit_price_centavos,ei.discount_centavos,ei.line_total_centavos from public.estimate_items ei left join public.job_order_items ji on ji.id=ei.job_order_item_id left join public.services s on s.id=ji.service_id left join public.service_categories sc on sc.id=s.category_id where ei.estimate_id=p_estimate_id;
else insert into public.invoice_items(invoice_id,organization_id,job_order_item_id,service_id,category_name_snapshot,description_snapshot,quantity,unit_price_centavos,discount_centavos,line_total_centavos)select inv,j.organization_id,ji.id,ji.service_id,coalesce(sc.name,'Uncategorized'),ji.service_name_snapshot,ji.quantity,ji.unit_price_centavos,ji.discount_centavos,ji.line_total_centavos from public.job_order_items ji left join public.services s on s.id=ji.service_id left join public.service_categories sc on sc.id=s.category_id where ji.job_order_id=j.id and ji.approval_status='approved';end if;
perform public.allocate_invoice_revenue(inv);return inv;end $$;

update public.invoice_items ii set recognized_revenue_centavos=ii.line_total_centavos;
do $$declare r record;begin for r in select id from public.invoices loop perform public.allocate_invoice_revenue(r.id);end loop;end$$;

create function public.get_invoice_revenue_breakdown(p_organization_id uuid,p_start_date date,p_end_date date,p_branch_id uuid default null)returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$declare result jsonb;begin
if p_end_date<p_start_date or not public.has_permission(p_organization_id,'reports.view')then raise exception 'Reporting access required' using errcode='42501';end if;
with lines as(select ii.description_snapshot service,coalesce(ii.category_name_snapshot,'Uncategorized')category,ii.quantity,ii.recognized_revenue_centavos from public.invoice_items ii join public.invoices i on i.id=ii.invoice_id join public.branches b on b.id=i.branch_id where i.organization_id=p_organization_id and i.status<>'void' and i.issued_at is not null and(i.issued_at at time zone b.timezone)::date between p_start_date and p_end_date and(p_branch_id is null or i.branch_id=p_branch_id)and public.can_access_branch(p_organization_id,i.branch_id))select jsonb_build_object('services',(select coalesce(jsonb_agg(to_jsonb(x)order by x."revenueCentavos" desc),'[]')from(select service,category,sum(recognized_revenue_centavos)::bigint "revenueCentavos",sum(quantity)::bigint quantity from lines group by service,category)x),'categories',(select coalesce(jsonb_agg(to_jsonb(x)order by x."revenueCentavos" desc),'[]')from(select category,sum(recognized_revenue_centavos)::bigint "revenueCentavos" from lines group by category)x))into result;return result;end$$;
revoke all on function public.get_invoice_revenue_breakdown(uuid,date,date,uuid)from public,anon;grant execute on function public.get_invoice_revenue_breakdown(uuid,date,date,uuid)to authenticated;

alter table public.plans add column provider_monthly_price_id text;
alter table public.plans add column provider_yearly_price_id text;
alter table public.plans add column is_custom boolean not null default false;
alter table public.organization_subscriptions add column trial_ends_at timestamptz;
alter table public.organization_subscriptions add column grace_ends_at timestamptz;
alter table public.organization_subscriptions add column provider_price_id text;
alter table public.organization_subscriptions add column billing_interval text check(billing_interval in('month','year'));
alter table public.organization_subscriptions add column last_reconciled_at timestamptz;
alter table public.organization_subscriptions add column provider_state_updated_at timestamptz;
create unique index organization_subscriptions_provider_customer_unique on public.organization_subscriptions(provider,provider_customer_id)where provider_customer_id is not null;
create unique index organization_subscriptions_provider_subscription_unique on public.organization_subscriptions(provider,provider_subscription_id)where provider_subscription_id is not null;
insert into public.plans(id,name,monthly_price_centavos,yearly_price_centavos,limits,features,is_custom,sort_order)values('multi_branch','Multi-Branch',0,null,'{"branches":-1,"staff":-1,"monthly_jobs":-1,"storage_mb":-1}'::jsonb,'{"public_page":true,"reminders":true,"advanced_reports":true,"ai":true}'::jsonb,true,40)on conflict(id)do nothing;
update public.plans set limits=limits||'{"storage_mb":100}'::jsonb where id='free';update public.plans set limits=limits||'{"storage_mb":1000}'::jsonb where id='starter';update public.plans set limits=limits||'{"storage_mb":5000}'::jsonb where id='business';update public.plans set limits=limits||'{"storage_mb":20000}'::jsonb where id='pro';

create function public.effective_entitlements(p_organization_id uuid)returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
select jsonb_build_object('planId',p.id,'planName',p.name,'status',coalesce(s.status,'free'),'limits',p.limits,'features',p.features,'currentPeriodEnd',s.current_period_end,'cancelAtPeriodEnd',coalesce(s.cancel_at_period_end,false),'graceEndsAt',s.grace_ends_at)
from public.plans p left join public.organization_subscriptions s on s.organization_id=p_organization_id
where p.id=case when s.status in('trialing','active')or(s.status='past_due' and s.grace_ends_at>now())then s.plan_id else 'free'end
limit 1 $$;
create function public.get_org_entitlements(p_organization_id uuid)returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$begin if not public.is_org_member(p_organization_id)then raise exception 'Organization not found' using errcode='42501';end if;return public.effective_entitlements(p_organization_id);end$$;
create function public.has_entitlement(p_organization_id uuid,p_feature text)returns boolean language sql stable security definer set search_path=public,pg_temp as $$select coalesce((public.effective_entitlements(p_organization_id)->'features'->>p_feature)::boolean,false)$$;
revoke all on function public.effective_entitlements(uuid),public.has_entitlement(uuid,text),public.get_org_entitlements(uuid)from public,anon;
grant execute on function public.get_org_entitlements(uuid)to authenticated;grant execute on function public.has_entitlement(uuid,text)to authenticated;

create function public.enforce_subscription_limits()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare lim integer;used integer;org uuid;begin if auth.uid() is null then return new;end if;org:=new.organization_id;if tg_table_name<>'organization_memberships' and not public.is_org_member(org)then return new;end if;if tg_table_name='branches'then lim:=coalesce((public.effective_entitlements(org)->'limits'->>'branches')::integer,1);select count(*)into used from public.branches where organization_id=org and is_active;if lim>=0 and used>=lim then raise exception 'Branch limit reached';end if;elsif tg_table_name='organization_memberships'then lim:=coalesce((public.effective_entitlements(org)->'limits'->>'staff')::integer,2);select count(*)into used from public.organization_memberships where organization_id=org and is_active;if lim>=0 and used>=lim then raise exception 'Staff limit reached';end if;end if;return new;end$$;
create trigger branch_subscription_limit before insert on public.branches for each row execute function public.enforce_subscription_limits();create trigger staff_subscription_limit before insert on public.organization_memberships for each row execute function public.enforce_subscription_limits();
create or replace function public.enforce_subscription_limits()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare lim integer;used integer;org uuid;zone text;begin if auth.uid() is null then return new;end if;org:=new.organization_id;if tg_table_name<>'organization_memberships' and not public.is_org_member(org)then return new;end if;if tg_table_name='branches'then lim:=coalesce((public.effective_entitlements(org)->'limits'->>'branches')::integer,1);select count(*)into used from public.branches where organization_id=org and is_active;if lim>=0 and used>=lim then raise exception 'Branch limit reached';end if;elsif tg_table_name='organization_memberships'then lim:=coalesce((public.effective_entitlements(org)->'limits'->>'staff')::integer,2);select count(*)into used from public.organization_memberships where organization_id=org and is_active;if lim>=0 and used>=lim then raise exception 'Staff limit reached';end if;elsif tg_table_name='job_orders'then lim:=coalesce((public.effective_entitlements(org)->'limits'->>'monthly_jobs')::integer,30);select timezone into zone from public.branches where id=new.branch_id;select count(*)into used from public.job_orders where organization_id=org and(created_at at time zone coalesce(zone,'Asia/Manila'))>=date_trunc('month',now()at time zone coalesce(zone,'Asia/Manila'));if lim>=0 and used>=lim then raise exception 'Monthly job limit reached';end if;end if;return new;end$$;
create trigger jobs_subscription_limit before insert on public.job_orders for each row execute function public.enforce_subscription_limits();
create function public.enforce_reminder_entitlement()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin if not public.has_entitlement(new.organization_id,'reminders')then raise exception 'Reminders require an eligible plan';end if;return new;end$$;
create trigger reminders_subscription_entitlement before insert on public.maintenance_reminders for each row execute function public.enforce_reminder_entitlement();
create function public.enforce_public_page_entitlement()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin if new.public_page_enabled and not old.public_page_enabled and not public.has_entitlement(new.id,'public_page')then raise exception 'Public page requires an eligible plan';end if;return new;end$$;
create trigger organization_public_page_entitlement before update of public_page_enabled on public.organizations for each row execute function public.enforce_public_page_entitlement();

create function public.apply_billing_subscription(p_provider text,p_event_id text,p_event_type text,p_payload_hash text,p_organization_id uuid,p_plan_id text,p_customer_id text,p_subscription_id text,p_status text,p_price_id text,p_interval text,p_period_start timestamptz,p_period_end timestamptz,p_cancel_at_period_end boolean,p_provider_updated_at timestamptz)returns boolean language plpgsql security definer set search_path=public,pg_temp as $$declare inserted_count integer;begin
if p_provider<>'stripe'or p_status not in('free','trialing','active','past_due','cancelled','paused')or not exists(select 1 from public.plans where id=p_plan_id and case when p_interval='year'then provider_yearly_price_id=p_price_id else provider_monthly_price_id=p_price_id end)then raise exception 'Invalid billing event';end if;
insert into public.billing_webhook_events(provider,provider_event_id,event_type,payload_hash)values(p_provider,p_event_id,p_event_type,p_payload_hash)on conflict do nothing;get diagnostics inserted_count=row_count;if inserted_count=0 then return false;end if;
insert into public.organization_subscriptions(organization_id,plan_id,provider,provider_customer_id,provider_subscription_id,status,provider_price_id,billing_interval,current_period_start,current_period_end,cancel_at_period_end,grace_ends_at,provider_state_updated_at,updated_at)values(p_organization_id,p_plan_id,p_provider,p_customer_id,p_subscription_id,p_status,p_price_id,p_interval,p_period_start,p_period_end,p_cancel_at_period_end,case when p_status='past_due'then now()+interval'7 days'else null end,p_provider_updated_at,now())on conflict(organization_id)do update set plan_id=excluded.plan_id,provider=excluded.provider,provider_customer_id=excluded.provider_customer_id,provider_subscription_id=excluded.provider_subscription_id,status=excluded.status,provider_price_id=excluded.provider_price_id,billing_interval=excluded.billing_interval,current_period_start=excluded.current_period_start,current_period_end=excluded.current_period_end,cancel_at_period_end=excluded.cancel_at_period_end,grace_ends_at=excluded.grace_ends_at,provider_state_updated_at=excluded.provider_state_updated_at,updated_at=now()where public.organization_subscriptions.provider_state_updated_at is null or public.organization_subscriptions.provider_state_updated_at<=excluded.provider_state_updated_at;
update public.billing_webhook_events set processed_at=now()where provider=p_provider and provider_event_id=p_event_id;insert into public.audit_events(organization_id,entity_type,entity_id,event_type,metadata)values(p_organization_id,'subscription',p_organization_id,'subscription.synced',jsonb_build_object('plan',p_plan_id,'status',p_status,'provider_event_id',p_event_id));return true;end$$;
revoke all on function public.apply_billing_subscription(text,text,text,text,uuid,text,text,text,text,text,text,timestamptz,timestamptz,boolean,timestamptz)from public,anon,authenticated;grant execute on function public.apply_billing_subscription(text,text,text,text,uuid,text,text,text,text,text,text,timestamptz,timestamptz,boolean,timestamptz)to service_role;

create policy subscriptions_owner_only on public.organization_subscriptions as restrictive for select to authenticated using(public.has_org_role(organization_id,array['owner']::public.organization_role[]));
revoke select on public.billing_webhook_events from anon,authenticated;
