import Link from "next/link";
import { FormMessage } from "@/components/form-message";
import { OpenQueueDisplay } from "@/components/open-queue-display";
import { EmptyState, PageHeader } from "@/components/page-patterns";
import { Button } from "@/components/ui/button";
import { getDashboardContext } from "@/lib/auth/context";
import { formatDuration,formatMoney,zonedDateTimeToUtc } from "@/lib/operations";
import { createClient } from "@/lib/supabase/server";
import { assignmentContextLabel, loadAppointmentAssignmentContext } from "@/modules/core/scheduling/appointment-assignment-view";
import { resolveIndustryConfig } from "@/modules/platform/industry";
import { salonAppointmentStatuses } from "@/modules/salon/appointments";

const PAGE_SIZE=25;
type AppointmentRow={id:string;status:string;source:string;starts_at:string|null;ends_at:string|null;expected_total_centavos:number;expected_duration_minutes:number|null;customers:{full_name:string}|{full_name:string}[]|null;vehicles?:{make:string|null;model:string|null;plate_number:string|null}|{make:string|null;model:string|null;plate_number:string|null}[]|null;appointment_services:{service_name_snapshot:string}[]};
type AppointmentView={appointment:AppointmentRow;customerName:string;vehicleName:string;services:string;staff:string;resources:string;time:string};

export default async function Page({searchParams}:{searchParams:Promise<{date?:string;view?:string;status?:string;q?:string;page?:string;message?:string;error?:string}>}) {
  const [params,{activeMembership},supabase]=await Promise.all([searchParams,getDashboardContext(),createClient()]);
  const config=resolveIndustryConfig(activeMembership.industry),salon=config.key==="salon";
  const date=/^\d{4}-\d{2}-\d{2}$/.test(params.date??"")?params.date!:new Intl.DateTimeFormat("en-CA",{timeZone:activeMembership.timezone}).format(new Date());
  const days=params.view==="week"?7:1,start=zonedDateTimeToUtc(`${date}T00:00`,activeMembership.timezone)!,end=new Date(start.valueOf()+days*86400000),page=Math.max(1,Number.parseInt(params.page??"1",10)||1),search=params.q?.trim().slice(0,100);
  let directory=supabase.from("appointment_directory").select("id",{count:"exact"}).eq("organization_id",activeMembership.organizationId).eq("branch_id",activeMembership.branchId).gte("starts_at",start.toISOString()).lt("starts_at",end.toISOString()).order("starts_at").range((page-1)*PAGE_SIZE,page*PAGE_SIZE-1);
  if(params.status) directory=directory.eq("status",params.status);
  if(search) directory=directory.ilike("search_document",`%${search.replace(/[,%()]/g," ")}%`);
  const {data:matches,count,error:searchError}=await directory,ids=matches?.map(match=>match.id)??[];
  const appointmentProjection=salon?"id,status,source,starts_at,ends_at,expected_total_centavos,expected_duration_minutes,customers(full_name),appointment_services(service_name_snapshot)":"id,status,source,starts_at,ends_at,expected_total_centavos,expected_duration_minutes,customers(full_name),vehicles(make,model,plate_number),appointment_services(service_name_snapshot)";
  const {data,error}=ids.length?await supabase.from("appointments").select(appointmentProjection).in("id",ids):{data:[],error:null};
  const assignmentContext=await loadAppointmentAssignmentContext(activeMembership.organizationId,ids);
  const rows=(data??[]) as unknown as AppointmentRow[],byId=new Map(rows.map(row=>[row.id,row]));
  const appointments=ids.map(id=>byId.get(id)).filter((row):row is AppointmentRow=>Boolean(row));
  const views:AppointmentView[]=appointments.map(appointment=>{
    const customer=Array.isArray(appointment.customers)?appointment.customers[0]:appointment.customers;
    const vehicle=Array.isArray(appointment.vehicles)?appointment.vehicles[0]:appointment.vehicles;
    const labels=assignmentContextLabel(assignmentContext.get(appointment.id)??{scheduledStaff:[],scheduledResources:[]});
    return {appointment,customerName:customer?.full_name??"Client not assigned",vehicleName:vehicle?[vehicle.make,vehicle.model,vehicle.plate_number&&`(${vehicle.plate_number})`].filter(Boolean).join(" "):"Vehicle not assigned",services:appointment.appointment_services.map(item=>item.service_name_snapshot).join(", "),staff:labels.staff,resources:labels.resources,time:new Intl.DateTimeFormat("en-PH",{timeZone:activeMembership.timezone,weekday:days>1?"short":undefined,hour:"numeric",minute:"2-digit"}).format(new Date(appointment.starts_at!))};
  });
  const canWrite=["owner","manager","advisor"].includes(activeMembership.role),pages=Math.max(1,Math.ceil((count??0)/PAGE_SIZE));
  const href=(target:number)=>{const next=new URLSearchParams();for(const [key,value] of Object.entries(params))if(value)next.set(key,value);next.set("page",String(target));return `?${next}`;};
  const statuses=salon?[...salonAppointmentStatuses]:["requested","confirmed","checked_in","queued","completed","cancelled","no_show"];

  return <main id={salon?"salon-appointments-page":"appointments-page"} className="mx-auto min-w-0 max-w-7xl"><PageHeader id={salon?"salon-appointments-page-header":"appointments-page-header"} eyebrow={activeMembership.branchName} title="Appointments" description={`Day and week agenda in ${activeMembership.timezone}.`} action={<div className="flex flex-wrap gap-2">{salon?<OpenQueueDisplay branchId={activeMembership.branchId}/>:null}{canWrite?<Button asChild><Link id={salon?"salon-appointment-create-button":"appointment-create-button"} href="/dashboard/appointments/new">New appointment</Link></Button>:null}</div>}/>
    <FormMessage message={params.message} error={params.error??(searchError||error?"Unable to load appointments.":undefined)}/>
    <form id={salon?"salon-appointments-filter-form":"appointments-filter-form"} className="mt-5 grid min-w-0 gap-3 rounded-ui-lg border border-admin-border bg-white p-3 sm:grid-cols-2 xl:grid-cols-[minmax(14rem,1fr)_auto_auto_auto_auto] xl:items-end"><label className="min-w-0 text-xs font-bold text-slate-600">Search<input id={salon?"salon-appointments-search-input":"appointments-search-input"} className="mt-1 min-h-11 w-full min-w-0 rounded-xl border border-zinc-200 bg-white px-3 text-zinc-950" name="q" defaultValue={params.q} placeholder={salon?"Client, phone, or treatment":"Customer, plate, vehicle, or service"}/></label><label className="text-xs font-bold text-slate-600">Date<input id={salon?"salon-appointments-date-input":"appointments-date-input"} className="mt-1 min-h-11 w-full rounded-xl border border-zinc-200 bg-white px-3" type="date" name="date" defaultValue={date}/></label><label className="text-xs font-bold text-slate-600">Range<select id={salon?"salon-appointments-view-select":"appointments-view-select"} className="mt-1 min-h-11 w-full rounded-xl border border-zinc-200 bg-white px-3" name="view" defaultValue={params.view??"day"}><option value="day">Day</option><option value="week">Week</option></select></label><label className="text-xs font-bold text-slate-600">Status<select id={salon?"salon-appointments-status-select":"appointments-status-select"} className="mt-1 min-h-11 w-full rounded-xl border border-zinc-200 bg-white px-3 capitalize" name="status" defaultValue={params.status??""}><option value="">All statuses</option>{statuses.map(status=><option key={status} value={status}>{status.replaceAll("_"," ")}</option>)}</select></label><Button id={salon?"salon-appointments-filter-button":"appointments-filter-button"} className="w-full xl:w-auto" variant="secondary" type="submit">Apply filters</Button></form>
    {salon?<SalonAppointmentViews views={views}/>:<div id="appointments-list" className="mt-6 grid gap-3">{views.map(view=><AppointmentCard key={view.appointment.id} view={view}/>)}</div>}
    {!searchError&&!error&&views.length===0&&<div className="mt-6"><EmptyState id={salon?"salon-appointments-empty-state":"appointments-empty-state"} title="No appointments scheduled" description={params.q||params.status?`No matching visits were found for this ${days>1?"week":"day"}. Try clearing the filters.`:`Create your first ${salon?"Client ":""}appointment to start managing the schedule.`} action={params.q||params.status?<Button asChild variant="secondary"><Link id={salon?"salon-appointments-clear-filters":"appointments-clear-filters"} href={`/dashboard/appointments?date=${date}&view=${params.view??"day"}`}>Clear filters</Link></Button>:canWrite?<Button asChild><Link id={salon?"salon-appointments-empty-create":"appointments-empty-create"} href="/dashboard/appointments/new">Create appointment</Link></Button>:undefined}/></div>}
    {pages>1&&<nav id={salon?"salon-appointments-pagination":undefined} aria-label="Appointment pages" className="mt-6 flex items-center justify-center gap-3"><Button asChild variant="secondary" disabled={page<=1}><Link href={href(Math.max(1,page-1))}>Previous</Link></Button><span className="text-sm font-semibold">Page {page} of {pages}</span><Button asChild variant="secondary" disabled={page>=pages}><Link href={href(Math.min(pages,page+1))}>Next</Link></Button></nav>}
  </main>;
}

function SalonAppointmentViews({views}:{views:AppointmentView[]}) { return <section id="salon-calendar" aria-label="Salon appointment calendar">
  <div id="salon-appointments-table-container" className="mt-6 hidden overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm md:block"><table id="salon-appointments-table" className="w-full text-left text-sm"><thead className="bg-zinc-50 text-xs uppercase tracking-wide text-zinc-500"><tr><th className="px-4 py-3">Time</th><th className="px-4 py-3">Client</th><th className="px-4 py-3">Treatment</th><th className="px-4 py-3">Staff / Station</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Estimate</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-zinc-100">{views.map(({appointment,customerName,services,staff,resources,time})=><tr id={`salon-appointment-row-${appointment.id}`} key={appointment.id}><td className="px-4 py-3 font-bold">{time}</td><td className="px-4 py-3 font-semibold">{customerName}</td><td className="max-w-64 px-4 py-3 text-zinc-600">{services}</td><td className="px-4 py-3 text-xs"><strong>{staff}</strong><span className="block text-zinc-500">{resources}</span></td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-bold capitalize ${appointment.status==="in_service"?"bg-amber-100 text-amber-900":appointment.status==="completed"?"bg-emerald-100 text-emerald-900":"bg-slate-100 text-slate-700"}`}>{appointment.status.replaceAll("_"," ")}</span></td><td className="px-4 py-3 text-right font-bold">{formatMoney(appointment.expected_total_centavos)}</td><td className="px-4 py-3 text-right"><Link id={`salon-appointment-view-${appointment.id}`} className="font-bold text-brand-primary-strong" href={`/dashboard/appointments/${appointment.id}`}>View</Link></td></tr>)}</tbody></table></div>
  <div id="salon-appointments-mobile-list" className="mt-6 grid gap-3 md:hidden">{views.map(view=><AppointmentCard key={view.appointment.id} view={view} salon/>)}</div>
</section>; }

function AppointmentCard({view,salon=false}:{view:AppointmentView;salon?:boolean}) { const {appointment,customerName,vehicleName,services,staff,resources,time}=view; return <Link id={`${salon?"salon-appointment":"appointment"}-card-${appointment.id}`} href={`/dashboard/appointments/${appointment.id}`} className="rounded-2xl border border-zinc-200 bg-white p-4 text-zinc-950 shadow-sm hover:border-brand-border sm:p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-semibold text-brand-primary-strong">{time}</p><h2 className="mt-1 truncate font-semibold">{salon?customerName:vehicleName}</h2><p className="truncate text-sm text-zinc-600">{salon?services:`${customerName} · ${services}`}</p><p id={`${salon?"salon-":""}appointment-assignment-context-${appointment.id}`} className="mt-2 truncate text-xs text-zinc-500"><strong>Staff:</strong> {staff} · <strong>{salon?"Station":"Service bay"}:</strong> {resources}</p></div><div className="shrink-0 text-right"><span className="rounded-full bg-zinc-100 px-2 py-1 text-xs font-bold capitalize">{appointment.status.replaceAll("_"," ")}</span><p className="mt-2 text-sm font-bold">{formatMoney(appointment.expected_total_centavos)}</p><p className="text-xs text-zinc-500">{appointment.expected_duration_minutes?formatDuration(appointment.expected_duration_minutes):"No estimate"}</p></div></div></Link>; }
