import Link from "next/link";
import { FormMessage } from "@/components/form-message";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { getDashboardContext } from "@/lib/auth/context";
import { formatDuration,formatMoney,zonedDateTimeToUtc } from "@/lib/operations";
import { createClient } from "@/lib/supabase/server";
import { automotiveAppointmentVehicleLabel } from "@/modules/automotive/appointments";
import { assignmentContextLabel, loadKarKRAppointmentAssignmentContext } from "@/modules/automotive/scheduling/appointment-operational-view";

const PAGE_SIZE=25;
export default async function Page({searchParams}:{searchParams:Promise<{date?:string;view?:string;status?:string;q?:string;page?:string;message?:string;error?:string}>}) {
  const [params,{activeMembership},supabase]=await Promise.all([searchParams,getDashboardContext(),createClient()]);
  const date=/^\d{4}-\d{2}-\d{2}$/.test(params.date??"")?params.date!:new Intl.DateTimeFormat("en-CA",{timeZone:activeMembership.timezone}).format(new Date());
  const days=params.view==="week"?7:1,start=zonedDateTimeToUtc(`${date}T00:00`,activeMembership.timezone)!,end=new Date(start.valueOf()+days*86400000),page=Math.max(1,Number.parseInt(params.page??"1",10)||1),search=params.q?.trim().slice(0,100);
  let directory=supabase.from("appointment_directory").select("id",{count:"exact"}).eq("organization_id",activeMembership.organizationId).eq("branch_id",activeMembership.branchId).gte("starts_at",start.toISOString()).lt("starts_at",end.toISOString()).order("starts_at").range((page-1)*PAGE_SIZE,page*PAGE_SIZE-1);
  if(params.status) directory=directory.eq("status",params.status); if(search) directory=directory.ilike("search_document",`%${search.replace(/[,%()]/g," ")}%`);
  const {data:matches,count,error:searchError}=await directory,ids=matches?.map(match=>match.id)??[];
  const {data,error}=ids.length?await supabase.from("appointments").select("id,status,source,starts_at,ends_at,expected_total_centavos,expected_duration_minutes,customers(full_name),vehicles(make,model,plate_number),appointment_services(service_name_snapshot)").in("id",ids):{data:[],error:null};
  const assignmentContext=await loadKarKRAppointmentAssignmentContext(activeMembership.organizationId,ids);
  const byId=new Map(data?.map(row=>[row.id,row])),appointments=ids.map(id=>byId.get(id)).filter((row):row is NonNullable<typeof row>=>Boolean(row)),canWrite=["owner","manager","advisor"].includes(activeMembership.role),pages=Math.max(1,Math.ceil((count??0)/PAGE_SIZE));
  const href=(target:number)=>{const next=new URLSearchParams();for(const [key,value] of Object.entries(params))if(value)next.set(key,value);next.set("page",String(target));return `?${next}`;};
  return <div id="appointments-page" className="mx-auto max-w-6xl"><div id="appointments-page-header" className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-amber-700">{activeMembership.branchName}</p><h1 className="mt-1 text-3xl font-black">Appointments</h1><p className="mt-2 text-zinc-600">Day and week agenda in {activeMembership.timezone}.</p></div>{canWrite&&<Button asChild><Link id="appointment-create-button" href="/dashboard/appointments/new">New appointment</Link></Button>}</div>
    <FormMessage message={params.message} error={params.error??(searchError||error?"Unable to load appointments.":undefined)}/>
    <form id="appointments-filter-form" className="mt-6 grid gap-2 sm:grid-cols-[1fr_auto_auto_auto_auto]"><input id="appointments-search-input" className="min-h-11 rounded-xl border border-zinc-200 bg-white px-3 text-zinc-950" name="q" defaultValue={params.q} placeholder="Customer, phone, plate, vehicle, or service"/><label className="text-sm font-semibold">Date<input id="appointments-date-input" className="ml-2 min-h-11 rounded-xl border border-zinc-200 bg-white px-3" type="date" name="date" defaultValue={date}/></label><select id="appointments-view-select" className="min-h-11 rounded-xl border border-zinc-200 bg-white px-3" name="view" defaultValue={params.view??"day"}><option value="day">Day</option><option value="week">Week</option></select><select id="appointments-status-select" className="min-h-11 rounded-xl border border-zinc-200 bg-white px-3" name="status" defaultValue={params.status??""}><option value="">All statuses</option>{["requested","confirmed","checked_in","queued","cancelled","no_show"].map(status=><option key={status} value={status}>{status.replaceAll("_"," ")}</option>)}</select><Button id="appointments-filter-button" variant="secondary" type="submit">View</Button></form>
    <div id="appointments-list" className="mt-6 grid gap-3">{appointments.map(appointment=>{const customer=Array.isArray(appointment.customers)?appointment.customers[0]:appointment.customers,vehicle=Array.isArray(appointment.vehicles)?appointment.vehicles[0]:appointment.vehicles,labels=assignmentContextLabel(assignmentContext.get(appointment.id)??{scheduledStaff:[],scheduledResources:[]});return <Link id={`appointment-card-${appointment.id}`} key={appointment.id} href={`/dashboard/appointments/${appointment.id}`} className="rounded-2xl border border-zinc-200 bg-white p-4 text-zinc-950 shadow-sm hover:border-amber-300 sm:p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-black text-amber-800">{new Intl.DateTimeFormat("en-PH",{timeZone:activeMembership.timezone,weekday:days>1?"short":undefined,hour:"numeric",minute:"2-digit"}).format(new Date(appointment.starts_at!))}</p><h2 id={`appointment-vehicle-value-${appointment.id}`} className="mt-1 truncate font-black">{automotiveAppointmentVehicleLabel(vehicle?{make:vehicle.make,model:vehicle.model,plateNumber:vehicle.plate_number}:null)}</h2><p className="truncate text-sm text-zinc-600">{customer?.full_name} · {appointment.appointment_services.map(item=>item.service_name_snapshot).join(", ")}</p><p id={`appointment-assignment-context-${appointment.id}`} className="mt-2 truncate text-xs text-zinc-500"><strong>Staff:</strong> {labels.staff} · <strong>Bay:</strong> {labels.resources}</p></div><div className="shrink-0 text-right"><span className="rounded-full bg-zinc-100 px-2 py-1 text-xs font-bold capitalize">{appointment.status.replaceAll("_"," ")}</span><p className="mt-2 text-sm font-bold">{formatMoney(appointment.expected_total_centavos)}</p><p className="text-xs text-zinc-500">{appointment.expected_duration_minutes?formatDuration(appointment.expected_duration_minutes):"No estimate"}</p></div></div></Link>})}{!searchError&&!error&&appointments.length===0&&<Card className="p-10 text-center"><h2 className="font-black">No appointments scheduled</h2><p className="mt-2 text-sm text-zinc-600">There are no matching visits for this {days>1?"week":"day"}.</p></Card>}</div>
    {pages>1&&<nav aria-label="Appointment pages" className="mt-6 flex items-center justify-center gap-3"><Button asChild variant="secondary" disabled={page<=1}><Link href={href(Math.max(1,page-1))}>Previous</Link></Button><span className="text-sm font-semibold">Page {page} of {pages}</span><Button asChild variant="secondary" disabled={page>=pages}><Link href={href(Math.min(pages,page+1))}>Next</Link></Button></nav>}
  </div>;
}
